// packages/kit/src/vue/Box.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  boxStyleEntries,
  type Align,
  type BoxBaseProps,
  type Justify,
} from '../layout';
import { isColorToken, resolveColorToken } from '../tokens';
import { useKitPalette, useKitScheme, type KitPalette } from './theme-context';

export type { Align, Justify };

export type Surface = 'none' | 'surface' | 'raised' | 'sunken' | 'toolbar';

const props = withDefaults(
  defineProps<
    BoxBaseProps & {
      surface?: Surface;
      tag?: string;
    }
  >(),
  { surface: 'none', tag: 'div' },
);

function surfaceColor(surface: Surface, palette: KitPalette): string | undefined {
  switch (surface) {
    case 'surface':
      return palette.bg;
    case 'raised':
      return palette.inputBg;
    case 'sunken':
      return palette.bg;
    case 'toolbar':
      return palette.toolbarBg;
    default:
      return undefined;
  }
}

const palette = useKitPalette();
const scheme = useKitScheme();

const style = computed<Record<string, string>>(() => {
  const override =
    props.background !== undefined && isColorToken(props.background)
      ? resolveColorToken(props.background, scheme)
      : props.background;
  const bg = override ?? surfaceColor(props.surface, palette);

  const entries = boxStyleEntries({
    direction: props.direction,
    gap: props.gap,
    padding: props.padding,
    margin: props.margin,
    align: props.align,
    justify: props.justify,
    flex: props.flex,
    wrap: props.wrap,
    background: bg,
    radius: props.radius,
    width: props.width,
    height: props.height,
    size: props.size,
    minWidth: props.minWidth,
    minHeight: props.minHeight,
    maxWidth: props.maxWidth,
    maxHeight: props.maxHeight,
    aspectRatio: props.aspectRatio,
  });

  const css: Record<string, string> = { display: 'flex' };
  for (const [k, v] of Object.entries(entries)) {
    css[k] = typeof v === 'number' ? `${v}px` : v;
  }
  return css;
});
</script>

<template>
  <component :is="tag" :style="style">
    <slot />
  </component>
</template>

// packages/kit/src/box.tsx
/** @file React Native Box/Row/Col layout primitives driving style through the shared `./layout` prop->style mapper (numbers are px); Box defaults to a column, Row/Col lock direction. */

import { View, type ViewProps, type ViewStyle } from 'react-native';
import {
  boxStyleEntries,
  type Align,
  type BoxBaseProps,
  type Justify,
} from './layout';
import { isColorToken, resolveColorToken } from './tokens';
import { useKitPalette, useKitScheme, type KitPalette } from './theme-context';

export type { Align, Justify };

/** Semantic surface variant resolved from the theme palette: none=transparent, surface/sunken=`bg`, raised=`inputBg` (cards/inputs/sheets), toolbar=`toolbarBg`. */
export type Surface = 'none' | 'surface' | 'raised' | 'sunken' | 'toolbar';

export type BoxProps = ViewProps &
  BoxBaseProps & {
    /** Semantic surface variant - resolves a background from the theme palette. Default `none` (transparent). A `background` override wins over it. */
    surface?: Surface;
  };

/** Resolve a surface variant to a palette background. `none` -> undefined. */
function surfaceColor(surface: Surface, palette: KitPalette): string | undefined {
  switch (surface) {
    case 'surface':
      return palette.bg;
    case 'raised':
      return palette.inputBg;
    case 'sunken':
      /** No dedicated pressed/well token; the recessed look reads as the base bg sitting under a raised surface. */
      return palette.bg;
    case 'toolbar':
      return palette.toolbarBg;
    default:
      return undefined;
  }
}

/** Flexbox layout primitive that maps shorthand spacing/alignment props to a React Native View style. */
export function Box({
  direction,
  gap,
  padding,
  margin,
  align,
  justify,
  flex,
  wrap,
  background,
  surface = 'none',
  radius,
  width,
  height,
  size,
  minWidth,
  minHeight,
  maxWidth,
  maxHeight,
  aspectRatio,
  style,
  children,
  ...rest
}: BoxProps) {
  const palette = useKitPalette();
  const scheme = useKitScheme();

  /** Precedence: explicit `background` override > semantic `surface` variant; a ColorToken background resolves scheme-aware here while kit `colors` keys and raw strings resolve in the mapper. */
  const override =
    background !== undefined && isColorToken(background)
      ? resolveColorToken(background, scheme)
      : background;
  const bg = override ?? surfaceColor(surface, palette);

  const computed = boxStyleEntries({
    direction,
    gap,
    padding,
    margin,
    align,
    justify,
    flex,
    wrap,
    background: bg,
    radius,
    width,
    height,
    size,
    minWidth,
    minHeight,
    maxWidth,
    maxHeight,
    aspectRatio,
  }) as ViewStyle;

  return (
    <View style={[computed, style]} {...rest}>
      {children}
    </View>
  );
}

export type RowColProps = Omit<BoxProps, 'direction'>;

/** Box variant locked to a horizontal (row) layout. */
export function Row(props: RowColProps) {
  return <Box direction="row" {...props} />;
}

/** Box variant locked to a vertical (column) layout. */
export function Col(props: RowColProps) {
  return <Box direction="col" {...props} />;
}
