// packages/kit/src/vue/Card.vue
<script setup lang="ts">
import { computed } from 'vue';
import Button from './Button.vue';
import { BLOCK_RADIUS_DEFAULT, FONT_SIZE, schemePalette } from '../tokens';

export type CardSize = 'sm' | 'md' | 'lg';

export interface CardStatus {
  text: string;
  favicon?: string;
}

export interface CardAction {
  label: string;
}

const props = withDefaults(
  defineProps<{
    size?: CardSize;
    padding?: number;
    background?: string;
    status?: CardStatus;
    collapsed?: boolean;
    confirm?: CardAction;
    cancel?: CardAction;
    pressable?: boolean;
    dark: boolean;
  }>(),
  { size: 'md', collapsed: false },
);

const emit = defineEmits<{ press: []; confirm: []; cancel: [] }>();

const PADDING: Record<CardSize, number> = { sm: 10, md: 14, lg: 18 };
const STATUS_SIZE: Record<CardSize, number> = {
  sm: FONT_SIZE['2xs'],
  md: FONT_SIZE.xs,
  lg: FONT_SIZE.sm,
};

const c = computed(() => schemePalette(props.dark));
const pad = computed(() => props.padding ?? PADDING[props.size]);

const style = computed<Record<string, string>>(() => ({
  backgroundColor: props.background ?? c.value.surface,
  borderColor: c.value.border,
  borderWidth: '1px',
  borderStyle: 'solid',
  borderRadius: `${BLOCK_RADIUS_DEFAULT}px`,
  padding: `${pad.value}px`,
  cursor: props.pressable ? 'pointer' : 'default',
}));

const statusStyle = computed<Record<string, string>>(() => ({
  color: c.value.sub,
  fontSize: `${STATUS_SIZE[props.size]}px`,
  fontFamily: 'Calibre-Medium',
  marginBottom: props.collapsed ? '0' : '8px',
  whiteSpace: 'nowrap',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
}));

const hasFoot = computed(() => Boolean(props.confirm) || Boolean(props.cancel));
</script>

<template>
  <component
    :is="pressable ? 'button' : 'div'"
    :style="style"
    @click="pressable ? emit('press') : undefined"
  >
    <div v-if="status" :style="statusStyle">
      <template v-if="status.favicon">{{ status.favicon }}&nbsp;&nbsp;</template>{{ status.text }}
    </div>
    <slot v-if="!collapsed" />
    <div
      v-if="hasFoot"
      :style="{ display: 'flex', flexDirection: 'row', justifyContent: 'flex-end', gap: '8px', marginTop: '12px' }"
    >
      <Button
        v-if="cancel"
        variant="secondary"
        size="sm"
        :label="cancel.label"
        :dark="dark"
        @click="emit('cancel')"
      />
      <Button
        v-if="confirm"
        variant="primary"
        size="sm"
        :label="confirm.label"
        :dark="dark"
        @click="emit('confirm')"
      />
    </div>
  </component>
</template>

// packages/kit/src/card.tsx

import { type ReactNode } from 'react';
import { Pressable, View, Text as RNText, type ViewStyle } from 'react-native';
import { Button } from './button';
import { BLOCK_RADIUS_DEFAULT, FONT_SIZE, schemePalette } from './tokens';

export type CardSize = 'sm' | 'md' | 'lg';

export interface CardStatus {
  text: string;
  favicon?: string;
}

export interface CardAction {
  label: string;
  onPress: () => void;
}

export interface CardProps {
  children?: ReactNode;
  size?: CardSize;
  padding?: number;
  background?: string;
  status?: CardStatus;
  collapsed?: boolean;
  asForm?: boolean;
  confirm?: CardAction;
  cancel?: CardAction;
  onPress?: () => void;
  dark: boolean;
  style?: ViewStyle;
}

const PADDING: Record<CardSize, number> = { sm: 10, md: 14, lg: 18 };
const STATUS_SIZE: Record<CardSize, number> = {
  sm: FONT_SIZE['2xs'],
  md: FONT_SIZE.xs,
  lg: FONT_SIZE.sm,
};

function palette(dark: boolean): { surface: string; border: string; sub: string } {
  const p = schemePalette(dark);
  return { surface: p.surface, border: p.border, sub: p.sub };
}

function CardStatusLine(props: {
  status: CardStatus;
  size: CardSize;
  collapsed: boolean;
  sub: string;
}): React.ReactElement {
  const { status, size, collapsed, sub } = props;
  return (
    <RNText
      style={{
        color: sub,
        fontSize: STATUS_SIZE[size],
        fontFamily: 'Calibre-Medium',
        marginBottom: collapsed ? 0 : 8,
      }}
      numberOfLines={1}
    >
      {status.favicon ? `${status.favicon}  ` : ''}
      {status.text}
    </RNText>
  );
}

function CardFoot(props: {
  confirm?: CardAction;
  cancel?: CardAction;
  dark: boolean;
}): React.ReactElement | null {
  const { confirm, cancel, dark } = props;
  if (!confirm && !cancel) return null;
  return (
    <View style={{ flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 12 }}>
      {cancel ? (
        <Button variant="secondary" size="sm" label={cancel.label} onPress={cancel.onPress} dark={dark} />
      ) : null}
      {confirm ? (
        <Button variant="primary" size="sm" label={confirm.label} onPress={confirm.onPress} dark={dark} />
      ) : null}
    </View>
  );
}

function CardBody(props: CardProps & { sub: string }): React.ReactElement {
  const { children, size = 'md', status, collapsed = false, confirm, cancel, dark, sub } = props;
  return (
    <>
      {status ? <CardStatusLine status={status} size={size} collapsed={collapsed} sub={sub} /> : null}
      {collapsed ? null : children}
      <CardFoot confirm={confirm} cancel={cancel} dark={dark} />
    </>
  );
}

export function Card(props: CardProps): React.ReactElement {
  const { size = 'md', padding, background, onPress, dark, style } = props;

  const c = palette(dark);
  const pad = padding ?? PADDING[size];

  const body = <CardBody {...props} sub={c.sub} />;

  const base: ViewStyle = {
    backgroundColor: background ?? c.surface,
    borderColor: c.border,
    borderWidth: 1,
    borderRadius: BLOCK_RADIUS_DEFAULT,
    padding: pad,
  };

  if (onPress) {
    return (
      <Pressable
        onPress={onPress}
        style={({ pressed }) => [base, { opacity: pressed ? 0.85 : 1 }, style]}
      >
        {body}
      </Pressable>
    );
  }

  return <View style={[base, style]}>{body}</View>;
}
