// packages/kit/src/vue/Textarea.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import {
  CONTROL_SIZES,
  controlBoxStyle,
  controlColors,
  controlTextStyle,
  type ControlSize,
  type ControlVariant,
} from '../control.styles';
import { BLOCK_RADIUS_DEFAULT } from '../tokens';

function lineHeight(size: ControlSize): number {
  return Math.round(CONTROL_SIZES[size].fontSize * 1.4);
}

const props = withDefaults(
  defineProps<{
    name?: string;
    modelValue?: string;
    placeholder?: string;
    variant?: ControlVariant;
    size?: ControlSize;
    disabled?: boolean;
    rows?: number;
    maxRows?: number;
    autoResize?: boolean;
    autoFocus?: boolean;
    required?: boolean;
    radius?: number;
    dark?: boolean;
  }>(),
  { variant: 'soft', size: 'md', rows: 3, autoResize: true, dark: false },
);

const emit = defineEmits<{ 'update:modelValue': [value: string] }>();

const focused = ref(false);
const fieldId = computed(() => (props.name ? `input-${props.name}` : undefined));

const colors = computed(() => controlColors(props.variant, props.dark));
const corner = computed(() => props.radius ?? BLOCK_RADIUS_DEFAULT);

function toCss(entries: Record<string, string | number>): Record<string, string> {
  const css: Record<string, string> = {};
  for (const [k, v] of Object.entries(entries)) {
    css[k] = typeof v === 'number' ? `${v}px` : v;
  }
  return css;
}

function resolveHeight(): number {
  const lh = lineHeight(props.size);
  const minH = props.rows * lh;
  if (!props.autoResize) return minH;
  const maxH = props.maxRows ? props.maxRows * lh : Number.MAX_SAFE_INTEGER;
  return Math.min(Math.max(minH, minH), maxH);
}

const style = computed<Record<string, string>>(() => {
  const box = controlBoxStyle(props.size, props.variant, colors.value, corner.value, focused.value);
  const text = controlTextStyle(props.size, colors.value);
  const css = {
    ...toCss(box as Record<string, string | number>),
    ...toCss(text as Record<string, string | number>),
  };
  css.borderStyle = 'solid';
  css.outline = 'none';
  css.width = '100%';
  css.resize = props.autoResize ? 'vertical' : 'none';
  css.fontFamily = 'Calibre-Medium';
  if (props.autoResize) {
    css.minHeight = `${resolveHeight()}px`;
    if (props.maxRows) css.maxHeight = `${props.maxRows * lineHeight(props.size)}px`;
  } else {
    css.height = `${resolveHeight()}px`;
  }
  if (props.disabled) css.opacity = '0.5';
  return css;
});

function onInput(event: Event): void {
  emit('update:modelValue', (event.target as HTMLTextAreaElement).value);
}
</script>

<template>
  <textarea
    :id="fieldId"
    :name="name"
    :value="modelValue"
    :placeholder="placeholder"
    :disabled="disabled"
    :required="required"
    :autofocus="autoFocus"
    :rows="rows"
    :style="style"
    @input="onInput"
    @focus="focused = true"
    @blur="focused = false"
  />
</template>

// packages/kit/src/textarea.tsx

import { forwardRef, useState } from 'react';
import {
  TextInput,
  type TextInputProps,
  type StyleProp,
  type TextStyle,
} from 'react-native';

type FocusEv = Parameters<NonNullable<TextInputProps['onFocus']>>[0];
type ContentSizeEv = Parameters<NonNullable<TextInputProps['onContentSizeChange']>>[0];
import {
  CONTROL_SIZES,
  controlBoxStyle,
  controlColors,
  controlTextStyle,
  type ControlSize,
  type ControlVariant,
} from './control.styles';
import { BLOCK_RADIUS_DEFAULT } from './tokens';

function lineHeight(size: ControlSize): number {
  return Math.round(CONTROL_SIZES[size].fontSize * 1.4);
}

export interface TextareaProps {
  name?: string;
  defaultValue?: string;
  value?: string;
  placeholder?: string;
  variant?: ControlVariant;
  size?: ControlSize;
  disabled?: boolean;
  rows?: number;
  maxRows?: number;
  autoResize?: boolean;
  autoFocus?: boolean;
  autoSelect?: boolean;
  required?: boolean;
  pattern?: string;
  radius?: number;
  onChangeText?: (text: string) => void;
  dark?: boolean;
  placeholderTextColor?: string;
  style?: StyleProp<TextStyle>;
  inputProps?: Omit<
    TextInputProps,
    'value' | 'defaultValue' | 'onChangeText' | 'style' | 'placeholder' | 'editable' | 'multiline'
  >;
}

function fieldIds(name: string | undefined): { nativeID?: string; accessibilityLabelledBy?: string } {
  if (!name) return {};
  return { nativeID: `input-${name}`, accessibilityLabelledBy: `label-${name}` };
}

function chainFocus(
  focused: boolean,
  setFocused: (v: boolean) => void,
  next: ((e: FocusEv) => void) | undefined,
  e: FocusEv,
): void {
  setFocused(focused);
  next?.(e);
}

function resolveHeight(
  size: ControlSize,
  rows: number,
  maxRows: number | undefined,
  autoResize: boolean,
  contentHeight: number | undefined,
): number {
  const lh = lineHeight(size);
  const minH = rows * lh;
  if (!autoResize) return minH;
  const maxH = maxRows ? maxRows * lh : Number.MAX_SAFE_INTEGER;
  return Math.min(Math.max(contentHeight ?? minH, minH), maxH);
}

export const Textarea = forwardRef<TextInput, TextareaProps>(function Textarea(props, ref) {
  const {
    name,
    defaultValue,
    value,
    placeholder,
    variant = 'soft',
    size = 'md',
    disabled,
    rows = 3,
    maxRows,
    autoResize = true,
    autoFocus,
    autoSelect,
    radius,
    onChangeText,
    dark = false,
    placeholderTextColor,
    style,
    inputProps,
  } = props;

  const [contentHeight, setContentHeight] = useState<number | undefined>(undefined);
  const [focused, setFocused] = useState(false);
  const colors = controlColors(variant, dark);
  const corner = radius ?? BLOCK_RADIUS_DEFAULT;
  const box = controlBoxStyle(size, variant, colors, corner, focused);
  const text = controlTextStyle(size, colors);

  const resolvedH = resolveHeight(size, rows, maxRows, autoResize, contentHeight);

  function handleContentSize(e: ContentSizeEv): void {
    if (autoResize) setContentHeight(e.nativeEvent.contentSize.height);
    inputProps?.onContentSizeChange?.(e);
  }

  return (
    <TextInput
      {...inputProps}
      ref={ref}
      multiline
      {...fieldIds(name)}
      value={value}
      defaultValue={defaultValue}
      placeholder={placeholder}
      placeholderTextColor={placeholderTextColor ?? colors.placeholder}
      editable={!disabled}
      autoFocus={autoFocus}
      selectTextOnFocus={autoSelect}
      onChangeText={onChangeText}
      onContentSizeChange={handleContentSize}
      onFocus={(e) => { chainFocus(true, setFocused, inputProps?.onFocus, e); }}
      onBlur={(e) => { chainFocus(false, setFocused, inputProps?.onBlur, e); }}
      textAlignVertical="top"
      style={[box, text, { height: resolvedH }, disabled && { opacity: 0.5 }, style]}
    />
  );
});
