// packages/kit/src/react-native/audio-player.tsx

import { useEffect, useMemo, useRef, useState } from 'react';
import { FONT_SIZE, fontName } from '../tokens';
import { Pressable, Text as RNText, View } from 'react-native';
import { createAudioPlayer, type AudioPlayer as ExpoAudioPlayer, type AudioStatus } from 'expo-audio';
import { Icon } from './icon';

const DEFAULT_BAR_COUNT = 34;

export interface AudioPlayerProps {
  src: string;
  duration?: number;
  onPlay?: () => void;
  dark?: boolean;
  waveform?: boolean;
  bars?: number[];
  barCount?: number;
  accent?: string;
  onAccent?: string;
}

const WAVE_TRACK_H = 26;

function fmt(ms: number): string {
  const total = Math.round(ms / 1000);
  const m = Math.floor(total / 60);
  const s = total % 60;
  return `${m}:${s.toString().padStart(2, '0')}`;
}

interface AudioState {
  playing: boolean;
  position: number;
  duration: number;
  toggle: () => Promise<void>;
  seek: (fraction: number) => void;
}

function useAudio(src: string, onPlay?: () => void): AudioState {
  const playerRef = useRef<ExpoAudioPlayer | null>(null);
  const [playing, setPlaying] = useState(false);
  const [position, setPosition] = useState(0);
  const [duration, setDuration] = useState(0);

  useEffect(() => {
    return () => {
      playerRef.current?.remove();
      playerRef.current = null;
    };
  }, []);

  function onStatus(status: AudioStatus): void {
    if (!status.isLoaded) return;
    setPosition(Math.round(status.currentTime * 1000));
    if (Number.isFinite(status.duration) && status.duration > 0) setDuration(Math.round(status.duration * 1000));
    if (status.didJustFinish) {
      setPlaying(false);
      setPosition(0);
      playerRef.current?.pause();
      void playerRef.current?.seekTo(0);
    } else {
      setPlaying(status.playing);
    }
  }

  function toggle(): Promise<void> {
    const current = playerRef.current;
    if (current === null) {
      onPlay?.();
      const player = createAudioPlayer({ uri: src });
      player.addListener('playbackStatusUpdate', onStatus);
      playerRef.current = player;
      player.play();
      return Promise.resolve();
    }
    if (playing) current.pause();
    else {
      onPlay?.();
      current.play();
    }
    return Promise.resolve();
  }

  function seek(fraction: number): void {
    if (!playerRef.current || duration <= 0) return;
    const clamped = Math.max(0, Math.min(1, fraction));
    void playerRef.current.seekTo(Math.floor(clamped * duration) / 1000);
  }

  return { playing, position, duration, toggle, seek };
}

function WaveformPlayer(props: AudioPlayerProps): React.ReactElement {
  const { src, onPlay, accent = '#0a7cff', onAccent = '#ffffff' } = props;
  const count = props.barCount ?? DEFAULT_BAR_COUNT;
  const { playing, position, duration, toggle, seek } = useAudio(src, onPlay);
  const [barWidth, setBarWidth] = useState(0);
  const bars = useMemo(
    () =>
      props.bars && props.bars.length > 0
        ? props.bars
        : new Array<number>(count).fill(0.5),
    [props.bars, count],
  );

  const progress = duration > 0 ? Math.min(position / duration, 1) : 0;
  const fallbackMs = (props.duration ?? 0) * 1000 || duration;
  const label = playing || position > 0 ? fmt(position) : fmt(fallbackMs);

  return (
    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 }}>
      <Pressable
        accessibilityRole="button"
        onPress={() => {
          void toggle();
        }}
        hitSlop={8}
        style={{
          width: 34,
          height: 34,
          borderRadius: 17,
          backgroundColor: onAccent,
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <Icon name={playing ? 'pause' : 'play'} size={18} color={accent} />
      </Pressable>
      <Pressable
        style={{ flex: 1, height: WAVE_TRACK_H, justifyContent: 'center' }}
        onLayout={(ev) => {
          setBarWidth(ev.nativeEvent.layout.width);
        }}
        onPress={(ev) => {
          if (barWidth > 0) seek(ev.nativeEvent.locationX / barWidth);
        }}
      >
        <View style={{ height: WAVE_TRACK_H, flexDirection: 'row', alignItems: 'center', gap: 2 }}>
          {bars.map((h, i) => {
            const filled = i / bars.length <= progress;
            return (
              <View
                key={i}
                style={{
                  flex: 1,
                  height: Math.max(3, h * WAVE_TRACK_H),
                  borderRadius: 1,
                  backgroundColor: onAccent,
                  opacity: filled ? 1 : 0.45,
                }}
              />
            );
          })}
        </View>
      </Pressable>
      <RNText
        style={{
          color: onAccent,
          fontSize: FONT_SIZE.xs,
          minWidth: 34,
          textAlign: 'right',
          fontFamily: 'Calibre-Regular',
        }}
      >
        {label}
      </RNText>
    </View>
  );
}

function BasicPlayer(props: {
  src: string;
  duration?: number;
  onPlay?: () => void;
  dark: boolean;
}): React.ReactElement {
  const { src, duration, onPlay, dark } = props;
  const { playing, position, duration: liveDuration, toggle } = useAudio(src, onPlay);
  const lengthMs = liveDuration > 0 ? liveDuration : (duration ?? 0) * 1000;
  const progress = lengthMs > 0 ? Math.min(position / lengthMs, 1) : 0;

  const fg = dark ? '#ffffff' : '#000000';
  const trackBg = dark ? '#3a3c40' : '#d8d8da';

  return (
    <View
      style={{
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        padding: 10,
        borderRadius: 12,
        backgroundColor: dark ? '#1c1c1e' : '#f0f0f2',
      }}
    >
      <Pressable
        accessibilityRole="button"
        onPress={() => {
          void toggle();
        }}
      >
        <Icon name={playing ? 'pause' : 'play'} size={22} color={fg} />
      </Pressable>
      <View style={{ flex: 1, height: 4, borderRadius: 2, backgroundColor: trackBg }}>
        <View
          style={{
            width: `${Math.round(progress * 100)}%`,
            height: 4,
            borderRadius: 2,
            backgroundColor: fg,
          }}
        />
      </View>
      <RNText style={{ color: fg, fontSize: FONT_SIZE.xs, fontFamily: fontName.sans }}>
        {fmt(lengthMs)}
      </RNText>
    </View>
  );
}

export function AudioPlayer(props: AudioPlayerProps): React.ReactElement {
  if (props.waveform) return <WaveformPlayer {...props} />;
  const { src, duration, onPlay, dark = false } = props;
  return <BasicPlayer src={src} duration={duration} onPlay={onPlay} dark={dark} />;
}

// packages/kit/src/vue/AudioPlayer.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue';
import { useKitScheme } from './theme-context';

const props = withDefaults(
  defineProps<{
    src: string;
    duration?: number;
    dark?: boolean;
    waveform?: boolean;
    bars?: number[];
    barCount?: number;
    accent?: string;
    onAccent?: string;
  }>(),
  {},
);

const emit = defineEmits<{ play: [] }>();

const scheme = useKitScheme();
const isDark = computed(() => props.dark ?? scheme === 'dark');

const accent = computed(() => props.accent ?? '#0a7cff');
const onAccent = computed(() => props.onAccent ?? '#ffffff');

const audio = ref<HTMLAudioElement | null>(null);
const playing = ref(false);
const position = ref(0);
const duration = ref(0);

const bars = computed(() =>
  props.bars && props.bars.length > 0
    ? props.bars
    : new Array<number>(props.barCount ?? 34).fill(0.5),
);
const progress = computed(() =>
  duration.value > 0 ? Math.min(position.value / duration.value, 1) : 0,
);

function fmt(ms: number): string {
  if (!ms || ms <= 0) return '0:00';
  const s = Math.round(ms / 1000);
  return `${Math.floor(s / 60)}:${(s % 60).toString().padStart(2, '0')}`;
}

const label = computed(() =>
  playing.value || position.value > 0
    ? fmt(position.value * 1000)
    : fmt((props.duration ?? 0) * 1000 || duration.value * 1000),
);

function toggle(): void {
  const el = audio.value;
  if (!el) return;
  if (el.paused) {
    emit('play');
    void el.play().catch(() => undefined);
  } else el.pause();
}

function onTime(): void {
  const el = audio.value;
  if (!el) return;
  position.value = el.currentTime;
  if (Number.isFinite(el.duration)) duration.value = el.duration;
}

function onEnded(): void {
  playing.value = false;
  position.value = 0;
}

function seek(ev: MouseEvent): void {
  const el = audio.value;
  if (!el || duration.value <= 0) return;
  const target = ev.currentTarget as HTMLElement;
  const rect = target.getBoundingClientRect();
  const fraction = Math.max(0, Math.min(1, (ev.clientX - rect.left) / rect.width));
  el.currentTime = fraction * duration.value;
  position.value = el.currentTime;
}

const wrapStyle = computed<Record<string, string>>(() => ({
  padding: '10px',
  borderRadius: '12px',
  backgroundColor: isDark.value ? '#1c1c1e' : '#f0f0f2',
}));

onBeforeUnmount(() => {
  audio.value?.pause();
});
</script>

<template>
  <Row v-if="props.waveform" class="items-center gap-2.5 flex-1">
    <audio
      ref="audio"
      :src="props.src"
      preload="metadata"
      class="hidden"
      @play="playing = true"
      @pause="playing = false"
      @timeupdate="onTime"
      @loadedmetadata="onTime"
      @ended="onEnded"
    />
    <Pressable
      tag="button"
      type="button"
      class="w-[34px] h-[34px] shrink-0 rounded-full flex items-center justify-center"
      :style="{ backgroundColor: onAccent }"
      :title="playing ? 'Pause' : 'Play'"
      @click="toggle"
    >
      <Icon :name="playing ? 'pause' : 'play'" :size="18" :color="accent" />
    </Pressable>
    <Pressable
      tag="button"
      type="button"
      class="flex-1 h-[26px] flex items-center gap-[2px] cursor-pointer bg-transparent border-0 p-0"
      @click="seek"
    >
      <span
        v-for="(h, i) in bars"
        :key="i"
        class="flex-1 rounded-[1px]"
        :style="{
          height: `${Math.max(3, h * 26)}px`,
          backgroundColor: onAccent,
          opacity: i / bars.length <= progress ? 1 : 0.45,
        }"
      />
    </Pressable>
    <span class="text-xs min-w-[34px] text-right font-sans" :style="{ color: onAccent }">{{ label }}</span>
  </Row>
  <div v-else :style="wrapStyle">
    <audio
      :src="src"
      controls
      preload="metadata"
      :style="{ width: '100%', height: '36px' }"
      @play="emit('play')"
    />
  </div>
</template>
