// packages/kit/src/react-native/avatar-stack.tsx

import { Text as RNText, View } from 'react-native';
import { AvatarView } from './avatar.view';

export interface AvatarStackEntry {
  src?: string;
  fallback?: string;
}

export interface AvatarStackProps {
  items: AvatarStackEntry[];
  size?: number;
  max?: number;
  overlap?: number;
  dark?: boolean;
}

export function AvatarStack(props: AvatarStackProps): React.ReactElement {
  const { items, size = 32, max = 4, overlap = 10, dark = false } = props;
  const shown = items.slice(0, max);
  const extra = items.length - shown.length;
  const ring = dark ? '#000000' : '#ffffff';
  return (
    <View style={{ flexDirection: 'row', alignItems: 'center' }}>
      {shown.map((item, index) => (
        <View
          key={index}
          style={{
            marginLeft: index === 0 ? 0 : -overlap,
            borderRadius: size,
            borderWidth: 2,
            borderColor: ring,
          }}
        >
          {item.src ? (
            <AvatarView src={item.src} size={size} />
          ) : (
            <View
              style={{
                width: size,
                height: size,
                borderRadius: size / 2,
                backgroundColor: dark ? '#3a3c40' : '#d8d8da',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <RNText
                style={{
                  color: dark ? '#ffffff' : '#000000',
                  fontSize: size * 0.4,
                  fontFamily: 'Calibre-Semibold',
                }}
              >
                {(item.fallback ?? '?').slice(0, 2)}
              </RNText>
            </View>
          )}
        </View>
      ))}
      {extra > 0 ? (
        <View
          style={{
            marginLeft: -overlap,
            width: size,
            height: size,
            borderRadius: size / 2,
            borderWidth: 2,
            borderColor: ring,
            backgroundColor: dark ? '#1c1c1e' : '#f0f0f2',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <RNText
            style={{
              color: dark ? '#ffffff' : '#000000',
              fontSize: size * 0.34,
              fontFamily: 'Calibre-Semibold',
            }}
          >
            {`+${extra}`}
          </RNText>
        </View>
      ) : null}
    </View>
  );
}

// packages/kit/src/vue/AvatarStack.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useKitScheme } from './theme-context';
import type { AvatarStackItem } from '../kit';

const props = withDefaults(
  defineProps<{
    items: AvatarStackItem[];
    size?: number;
    max?: number;
    overlap?: number;
    dark?: boolean;
  }>(),
  { size: 32, max: 4, overlap: 10 },
);

const scheme = useKitScheme();
const isDark = computed(() => props.dark ?? scheme === 'dark');

const shown = computed(() => props.items.slice(0, props.max));
const extra = computed(() => props.items.length - shown.value.length);
const ring = computed(() => (isDark.value ? '#000000' : '#ffffff'));

function cellStyle(index: number): Record<string, string> {
  return {
    marginLeft: index === 0 ? '0' : `-${props.overlap}px`,
    width: `${props.size}px`,
    height: `${props.size}px`,
    borderRadius: '50%',
    border: `2px solid ${ring.value}`,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: isDark.value ? '#3a3c40' : '#d8d8da',
    color: isDark.value ? '#ffffff' : '#000000',
    fontFamily: 'Calibre-Semibold',
    fontSize: `${props.size * 0.4}px`,
    boxSizing: 'border-box',
  };
}

const moreStyle = computed<Record<string, string>>(() => ({
  marginLeft: `-${props.overlap}px`,
  width: `${props.size}px`,
  height: `${props.size}px`,
  borderRadius: '50%',
  border: `2px solid ${ring.value}`,
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: isDark.value ? '#1c1c1e' : '#f0f0f2',
  color: isDark.value ? '#ffffff' : '#000000',
  fontFamily: 'Calibre-Semibold',
  fontSize: `${props.size * 0.34}px`,
  boxSizing: 'border-box',
}));
</script>

<template>
  <div :style="{ display: 'inline-flex', flexDirection: 'row', alignItems: 'center' }">
    <span v-for="(item, index) in shown" :key="index" :style="cellStyle(index)">
      <img
        v-if="item.src"
        :src="item.src"
        alt=""
        :style="{ width: '100%', height: '100%', objectFit: 'cover' }"
      />
      <template v-else>{{ (item.fallback ?? '?').slice(0, 2) }}</template>
    </span>
    <span v-if="extra > 0" :style="moreStyle">+{{ extra }}</span>
  </div>
</template>
