// packages/kit/src/react-native/checkbox.tsx

import { useState } from 'react';
import { FONT_SIZE, fontName } from '../tokens';
import { Pressable, View, Text as RNText, type ViewStyle } from 'react-native';
import { Icon } from './icon';
import { styleList } from '../control.styles';

export interface CheckboxProps {
  name?: string;
  label?: string;
  defaultChecked?: boolean;
  checked?: boolean;
  disabled?: boolean;
  required?: boolean;
  onChange?: (checked: boolean) => void;
  size?: number;
  dark?: boolean;
  style?: ViewStyle | ViewStyle[];
}

function checkboxColors(dark: boolean): { head: string; bg: string; border: string } {
  return {
    head: dark ? '#ffffff' : '#000000',
    bg: dark ? '#0e0f10' : '#ffffff',
    border: dark ? '#282a2d' : '#e4e4e5',
  };
}

function boxStyle(
  size: number,
  checked: boolean,
  colors: { head: string; bg: string; border: string },
): ViewStyle {
  return {
    width: size,
    height: size,
    borderRadius: 6,
    borderWidth: checked ? 0 : 1,
    borderColor: colors.border,
    backgroundColor: checked ? colors.head : colors.bg,
    alignItems: 'center',
    justifyContent: 'center',
  };
}

export function Checkbox(props: CheckboxProps): React.ReactElement {
  const {
    name,
    label,
    defaultChecked,
    checked: controlled,
    disabled,
    onChange,
    size = 20,
    dark = false,
    style,
  } = props;

  const [internal, setInternal] = useState(defaultChecked ?? false);
  const checked = controlled ?? internal;

  const { head, bg } = checkboxColors(dark);

  function toggle(): void {
    if (disabled) return;
    const next = !checked;
    if (controlled === undefined) setInternal(next);
    onChange?.(next);
  }

  const box = boxStyle(size, checked, checkboxColors(dark));

  return (
    <Pressable
      accessibilityRole="checkbox"
      accessibilityState={{ checked, disabled }}
      accessibilityLabel={label ?? name}
      disabled={disabled}
      onPress={toggle}
      style={[
        { flexDirection: 'row', alignItems: 'center', gap: 10, opacity: disabled ? 0.5 : 1 },
        ...styleList(style),
      ]}
    >
      <View style={box}>
        {checked ? <Icon name="check" size={size - 4} color={bg} /> : null}
      </View>
      {label ? (
        <RNText style={{ color: head, fontSize: FONT_SIZE.md, fontFamily: fontName.sans }}>{label}</RNText>
      ) : null}
    </Pressable>
  );
}

// packages/kit/src/vue/Checkbox.vue
<script setup lang="ts">
import { computed } from 'vue';
import Icon from './Icon.vue';

const props = withDefaults(
  defineProps<{
    name?: string;
    label?: string;
    modelValue?: boolean;
    disabled?: boolean;
    required?: boolean;
    size?: number;
    dark?: boolean;
  }>(),
  { size: 20, dark: false },
);

const emit = defineEmits<{ 'update:modelValue': [checked: boolean] }>();

function checkboxColors(dark: boolean): { head: string; bg: string; border: string } {
  return {
    head: dark ? '#ffffff' : '#000000',
    bg: dark ? '#0e0f10' : '#ffffff',
    border: dark ? '#282a2d' : '#e4e4e5',
  };
}

const colors = computed(() => checkboxColors(props.dark));
const checked = computed(() => props.modelValue ?? false);

const rootStyle = computed<Record<string, string>>(() => ({
  display: 'inline-flex',
  flexDirection: 'row',
  alignItems: 'center',
  gap: '10px',
  opacity: props.disabled ? '0.5' : '1',
  cursor: props.disabled ? 'default' : 'pointer',
  background: 'none',
  border: '0',
  padding: '0',
}));

const boxStyle = computed<Record<string, string>>(() => ({
  width: `${props.size}px`,
  height: `${props.size}px`,
  borderRadius: '6px',
  borderWidth: checked.value ? '0' : '1px',
  borderStyle: 'solid',
  borderColor: colors.value.border,
  backgroundColor: checked.value ? colors.value.head : colors.value.bg,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
}));

const labelStyle = computed<Record<string, string>>(() => ({
  color: colors.value.head,
  fontSize: '15px',
  fontFamily: 'Calibre-Medium',
}));

function toggle(): void {
  if (props.disabled) return;
  emit('update:modelValue', !checked.value);
}
</script>

<template>
  <button
    type="button"
    role="checkbox"
    :aria-checked="checked"
    :aria-label="label ?? name"
    :disabled="disabled"
    :style="rootStyle"
    @click="toggle"
  >
    <span :style="boxStyle">
      <Icon v-if="checked" name="check" :size="size - 4" :color="colors.bg" />
    </span>
    <span v-if="label" :style="labelStyle">{{ label }}</span>
  </button>
</template>
