// packages/kit/src/react-native/divider.tsx

import { View, type ViewStyle } from 'react-native';

export interface DividerProps {
  spacing?: number;
  color?: string;
  size?: number;
  flush?: number | boolean;
  dark: boolean;
  style?: ViewStyle;
}

function borderColor(dark: boolean): string {
  return dark ? '#282a2d' : '#e4e4e5';
}

export function Divider(props: DividerProps): React.ReactElement {
  const { spacing = 0, color, size = 1, flush = false, dark, style } = props;
  const bleed = flush === true ? 16 : typeof flush === 'number' ? flush : 0;

  const base: ViewStyle = {
    height: size,
    backgroundColor: color ?? borderColor(dark),
    marginVertical: spacing,
    marginHorizontal: bleed ? -bleed : 0,
  };

  return <View style={style ? [base, style] : base} />;
}

// packages/kit/src/vue/Divider.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = withDefaults(
  defineProps<{
    spacing?: number;
    color?: string;
    size?: number;
    flush?: number | boolean;
    dark: boolean;
  }>(),
  { spacing: 0, size: 1, flush: false },
);

function borderColor(dark: boolean): string {
  return dark ? '#282a2d' : '#e4e4e5';
}

const style = computed<Record<string, string>>(() => {
  const bleed = props.flush === true ? 16 : typeof props.flush === 'number' ? props.flush : 0;
  return {
    height: `${props.size}px`,
    backgroundColor: props.color ?? borderColor(props.dark),
    marginTop: `${props.spacing}px`,
    marginBottom: `${props.spacing}px`,
    marginLeft: bleed ? `${-bleed}px` : '0',
    marginRight: bleed ? `${-bleed}px` : '0',
  };
});
</script>

<template>
  <div :style="style" />
</template>
