// packages/kit/src/label.tsx
/**
 * @file Label — a hook-free ChatKit-styled form-field label that wires a `nativeID` from `fieldName` so RN screen readers associate the label with its control.
 */

import { Text as RNText, type TextStyle } from 'react-native';
import { type ReactNode } from 'react';

/** ChatKit TextSize. */
export type LabelSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
/** ChatKit Label weight set. */
export type LabelWeight = 'normal' | 'medium' | 'semibold' | 'bold';
/** ChatKit TextAlign. */
export type LabelAlign = 'start' | 'center' | 'end';

const SIZE: Record<LabelSize, number> = { xs: 12, sm: 13, md: 15, lg: 17, xl: 20 };
const FONT: Record<LabelWeight, string> = {
  normal: 'Calibre-Medium',
  medium: 'Calibre-Medium',
  semibold: 'Calibre-Semibold',
  bold: 'Calibre-Semibold',
};
const ALIGN: Record<LabelAlign, TextStyle['textAlign']> = {
  start: 'left',
  center: 'center',
  end: 'right',
};

export interface LabelProps {
  /** ChatKit: value. The label text (children also accepted). */
  value?: string;
  children?: ReactNode;
  /** ChatKit: fieldName. The `name` of the control this label is for. Used to derive the RN `nativeID` so screen readers can pair them. */
  fieldName?: string;
  /** ChatKit: size. Default 'md' (15). */
  size?: LabelSize;
  /** ChatKit: weight. Default 'medium'. */
  weight?: LabelWeight;
  /** ChatKit: textAlign. Default 'start'. */
  textAlign?: LabelAlign;
  /** ChatKit: color. Token/hex; falls back to the scheme head color. */
  color?: string;
  /** Effective color scheme. Pass useEffectiveColorScheme() === 'dark'. */
  dark?: boolean;
  /** Escape-hatch style merged last. */
  style?: TextStyle | TextStyle[];
}

/** Head Color. */
function headColor(dark: boolean): string {
  return dark ? '#ffffff' : '#000000';
}

/** ChatKit-style RN form-field label. */
export function Label(props: LabelProps): React.ReactElement {
  const {
    value,
    children,
    fieldName,
    size = 'md',
    weight = 'medium',
    textAlign = 'start',
    color,
    dark = false,
    style,
  } = props;

  const base: TextStyle = {
    color: color ?? headColor(dark),
    fontSize: SIZE[size],
    fontFamily: FONT[weight],
    textAlign: ALIGN[textAlign],
  };

  return (
    <RNText
      nativeID={fieldName ? `label-${fieldName}` : undefined}
      style={style ? [base, ...(Array.isArray(style) ? style : [style])] : base}
    >
      {value ?? children}
    </RNText>
  );
}

// packages/kit/src/vue/Label.vue
<script setup lang="ts">
import { computed } from 'vue';

export type LabelSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
export type LabelWeight = 'normal' | 'medium' | 'semibold' | 'bold';
export type LabelAlign = 'start' | 'center' | 'end';

const SIZE: Record<LabelSize, number> = { xs: 12, sm: 13, md: 15, lg: 17, xl: 20 };
const FONT: Record<LabelWeight, string> = {
  normal: 'Calibre-Medium',
  medium: 'Calibre-Medium',
  semibold: 'Calibre-Semibold',
  bold: 'Calibre-Semibold',
};
const ALIGN: Record<LabelAlign, string> = {
  start: 'left',
  center: 'center',
  end: 'right',
};

const props = withDefaults(
  defineProps<{
    value?: string;
    fieldName?: string;
    size?: LabelSize;
    weight?: LabelWeight;
    textAlign?: LabelAlign;
    color?: string;
    dark?: boolean;
  }>(),
  { size: 'md', weight: 'medium', textAlign: 'start', dark: false },
);

function headColor(dark: boolean): string {
  return dark ? '#ffffff' : '#000000';
}

const labelId = computed(() => (props.fieldName ? `label-${props.fieldName}` : undefined));

const style = computed<Record<string, string>>(() => ({
  color: props.color ?? headColor(props.dark),
  fontSize: `${SIZE[props.size]}px`,
  fontFamily: FONT[props.weight],
  textAlign: ALIGN[props.textAlign],
}));
</script>

<template>
  <label :id="labelId" :style="style"><slot>{{ value }}</slot></label>
</template>
