// packages/kit/src/react-native/list-view.tsx

import { Children, isValidElement, type ReactNode } from 'react';
import { Pressable, View, Text as RNText, type ViewStyle } from 'react-native';
import { FONT_SIZE, schemePalette } from '../tokens';

export type ListItemAlign = 'start' | 'center' | 'end';

const ROW_INSET = 16;

const ALIGN: Record<ListItemAlign, ViewStyle['alignItems']> = {
  start: 'flex-start',
  center: 'center',
  end: 'flex-end',
};

function palette(dark: boolean): { border: string; pressed: string; sub: string } {
  const p = schemePalette(dark);
  return { border: p.border, pressed: p.pressed, sub: p.sub };
}

export interface ListViewProps {
  children: ReactNode;
  limit?: number;
  status?: { text: string };
  dark: boolean;
  style?: ViewStyle;
}

export function ListView(props: ListViewProps): React.ReactElement {
  const { children, limit, status, dark, style } = props;
  const c = palette(dark);

  const items = Children.toArray(children).filter(isValidElement);
  const shown = limit !== undefined ? items.slice(0, limit) : items;

  return (
    <View style={style}>
      {shown.map((child, i) => (
        <View key={child.key ?? i}>
          {child}
          {i < shown.length - 1 ? (
            <View
              style={{
                height: 1,
                backgroundColor: c.border,
                marginHorizontal: ROW_INSET,
              }}
            />
          ) : null}
        </View>
      ))}
      {status ? (
        <RNText
          style={{
            color: c.sub,
            fontSize: FONT_SIZE.xs,
            fontFamily: 'Calibre-Medium',
            paddingVertical: 10,
            paddingHorizontal: 16,
          }}
          numberOfLines={1}
        >
          {status.text}
        </RNText>
      ) : null}
    </View>
  );
}

export interface ListViewItemProps {
  children: ReactNode;
  onPress?: () => void;
  gap?: number;
  align?: ListItemAlign;
  dark: boolean;
  style?: ViewStyle;
}

export function ListViewItem(props: ListViewItemProps): React.ReactElement {
  const { children, onPress, gap = 12, align = 'center', dark, style } = props;
  const c = palette(dark);

  const row: ViewStyle = {
    flexDirection: 'row',
    alignItems: ALIGN[align],
    gap,
    paddingVertical: 16,
    paddingHorizontal: ROW_INSET,
  };

  if (onPress) {
    return (
      <Pressable
        onPress={onPress}
        style={({ pressed }) => [
          row,
          { backgroundColor: pressed ? c.pressed : 'transparent' },
          style,
        ]}
      >
        {children}
      </Pressable>
    );
  }

  return <View style={[row, style]}>{children}</View>;
}

// packages/kit/src/vue/ListView.vue
<script setup lang="ts" generic="T">
import { computed } from 'vue';
import { FONT_SIZE, schemePalette } from '../tokens';

const ROW_INSET = 16;

const props = withDefaults(
  defineProps<{
    items?: T[];
    limit?: number;
    status?: { text: string };
    dark: boolean;
    keyField?: keyof T;
  }>(),
  { items: () => [] },
);

const c = computed(() => {
  const p = schemePalette(props.dark);
  return { border: p.border, sub: p.sub };
});

const shown = computed(() =>
  props.limit !== undefined ? props.items.slice(0, props.limit) : props.items,
);

function itemKey(item: T, index: number): string | number {
  if (props.keyField) {
    const k: unknown = item[props.keyField];
    if (typeof k === 'string' || typeof k === 'number') return k;
  }
  return index;
}

const dividerStyle = computed<Record<string, string>>(() => ({
  height: '1px',
  backgroundColor: c.value.border,
  marginLeft: `${ROW_INSET}px`,
  marginRight: `${ROW_INSET}px`,
}));

const statusStyle = computed<Record<string, string>>(() => ({
  color: c.value.sub,
  fontSize: `${FONT_SIZE.xs}px`,
  fontFamily: 'Calibre-Medium',
  paddingTop: '10px',
  paddingBottom: '10px',
  paddingLeft: '16px',
  paddingRight: '16px',
  whiteSpace: 'nowrap',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
}));
</script>

<template>
  <div>
    <div v-for="(item, index) in shown" :key="itemKey(item, index)">
      <slot name="item" :item="item" :index="index" />
      <div v-if="index < shown.length - 1" :style="dividerStyle" />
    </div>
    <div v-if="status" :style="statusStyle">{{ status.text }}</div>
  </div>
</template>
