// packages/kit/src/react-native/popover.tsx
import { useState, type ReactNode } from 'react';
import { Modal, Pressable, View } from 'react-native';
import { colors, schemePalette } from '../tokens';
import { Icon, type HeroIconName } from './icon';
import { Text } from './text';

export interface PopoverItemView {
  id: string;
  label: string;
  icon?: HeroIconName;
  danger?: boolean;
  disabled?: boolean;
  onPress: () => void;
}

export interface PopoverProps {
  trigger: ReactNode;
  items: PopoverItemView[];
  side?: 'top' | 'bottom';
  align?: 'start' | 'end';
  dark?: boolean;
}

export function Popover(props: PopoverProps): React.ReactElement {
  const { trigger, items, side = 'bottom', align = 'end', dark = false } = props;
  const [open, setOpen] = useState(false);
  const p = schemePalette(dark);
  const panelBg = dark ? colors['surface-dark'] : colors['bg-light'];
  const hoverBg = dark ? colors['hover-dark'] : colors['hover-light'];
  const danger = '#ef4444';
  const close = (): void => {
    setOpen(false);
  };
  const run = (item: PopoverItemView): void => {
    setOpen(false);
    item.onPress();
  };
  const vertical = side === 'top' ? { bottom: 52 } : { top: 52 };
  const horizontal = align === 'start' ? { left: 8 } : { right: 8 };
  return (
    <View>
      <Pressable
        onPress={() => {
          setOpen(true);
        }}
      >
        {trigger}
      </Pressable>
      <Modal visible={open} transparent animationType="fade" onRequestClose={close}>
        <Pressable style={{ flex: 1 }} onPress={close}>
          <Pressable
            onPress={() => undefined}
            style={{
              position: 'absolute',
              ...vertical,
              ...horizontal,
              minWidth: 200,
              paddingVertical: 4,
              borderRadius: 12,
              backgroundColor: panelBg,
              borderWidth: 1,
              borderColor: p.border,
              shadowColor: '#000000',
              shadowOpacity: 0.18,
              shadowRadius: 16,
              shadowOffset: { width: 0, height: 8 },
              elevation: 8,
            }}
          >
            {items.map((item) => (
              <Pressable
                key={item.id}
                disabled={item.disabled}
                onPress={() => {
                  run(item);
                }}
                style={({ pressed }) => ({
                  flexDirection: 'row',
                  alignItems: 'center',
                  gap: 12,
                  paddingHorizontal: 12,
                  paddingVertical: 10,
                  opacity: item.disabled === true ? 0.5 : 1,
                  backgroundColor: pressed ? hoverBg : 'transparent',
                })}
              >
                {item.icon === undefined ? null : (
                  <Icon
                    name={item.icon}
                    size={20}
                    color={item.danger === true ? danger : p.sub}
                  />
                )}
                <Text size="sm" color={item.danger === true ? danger : p.head}>
                  {item.label}
                </Text>
              </Pressable>
            ))}
          </Pressable>
        </Pressable>
      </Modal>
    </View>
  );
}

// packages/kit/src/vue/Popover.vue
<script setup lang="ts">
import { ref } from 'vue';
import KitNode from './KitNode.vue';
import Col from './Col.vue';
import Pressable from './Pressable.vue';
import Icon from './Icon.vue';
import {
  dispatchAction,
  type PopoverItem,
  type WidgetNode,
} from '../kit';
import { resolveIconName } from './kit-node-props';
import { useKitRender } from './kit-form-context';

const POPOVER_ITEM_PRESS = 'popover.item.press';

withDefaults(
  defineProps<{
    trigger: WidgetNode;
    items: PopoverItem[];
    side?: 'top' | 'bottom';
    align?: 'start' | 'end';
    title?: string;
  }>(),
  { title: 'More' },
);

const render = useKitRender();
const open = ref(false);

function close(): void {
  open.value = false;
}

function run(item: PopoverItem): void {
  open.value = false;
  if (item.disabled === true) return;
  const type = item.pressType ?? POPOVER_ITEM_PRESS;
  void dispatchAction(render.registry, { type, payload: item.payload }, {
    id: item.id,
  });
}
</script>

<template>
  <Pressable
    tag="button"
    type="button"
    class="p-2 rounded-lg text-metro-sub-light dark:text-metro-sub-dark
      hover:bg-metro-hover-light dark:hover:bg-metro-hover-dark"
    :title="title"
    @click="open = true"
  >
    <KitNode :node="trigger" />
  </Pressable>

  <template v-if="open">
    <Col class="fixed inset-0 z-40" @click="close" />
    <Col
      class="fixed z-50 min-w-[200px] py-1 rounded-lg shadow-lg
        bg-metro-bg-light dark:bg-metro-surface-dark
        border border-metro-border-light dark:border-metro-border-dark"
      :class="[
        side === 'top' ? 'bottom-[52px]' : 'top-[52px]',
        align === 'start' ? 'left-2' : 'right-2',
      ]"
    >
      <Pressable
        v-for="item in items"
        :key="item.id"
        tag="button"
        type="button"
        :disabled="item.disabled"
        class="w-full flex items-center gap-3 text-left px-3 py-2.5 text-sm disabled:opacity-50
          hover:bg-metro-hover-light dark:hover:bg-metro-hover-dark"
        :class="item.danger
          ? 'text-red-500'
          : 'text-metro-head-light dark:text-metro-head-dark'"
        @click="run(item)"
      >
        <Icon v-if="item.icon" :name="resolveIconName(item.icon)" :size="20" />
        {{ item.label }}
      </Pressable>
    </Col>
  </template>
</template>
