// packages/kit/src/radio-group.tsx

import { useState } from 'react';
import { Pressable, View, Text as RNText, type ViewStyle } from 'react-native';

export interface RadioOption {
  label: string;
  value: string;
  disabled?: boolean;
}

export interface RadioGroupProps {
  name?: string;
  options?: RadioOption[];
  defaultValue?: string;
  value?: string;
  direction?: 'row' | 'col';
  disabled?: boolean;
  required?: boolean;
  ariaLabel?: string;
  onChange?: (value: string) => void;
  size?: number;
  dark?: boolean;
  style?: ViewStyle | ViewStyle[];
}

function styleList(style: ViewStyle | ViewStyle[] | undefined): ViewStyle[] {
  if (!style) return [];
  return Array.isArray(style) ? style : [style];
}

function RadioOptionRow(props: {
  opt: RadioOption;
  selected: string | undefined;
  groupDisabled: boolean;
  size: number;
  head: string;
  border: string;
  onPick: (v: string) => void;
}): React.ReactElement {
  const { opt, selected, groupDisabled, size, head, border, onPick } = props;
  const isSel = opt.value === selected;
  const optDisabled = groupDisabled || (opt.disabled ?? false);
  const outer: ViewStyle = {
    width: size,
    height: size,
    borderRadius: size / 2,
    borderWidth: 1.5,
    borderColor: isSel ? head : border,
    alignItems: 'center',
    justifyContent: 'center',
  };
  return (
    <Pressable
      accessibilityRole="radio"
      accessibilityState={{ selected: isSel, disabled: optDisabled }}
      accessibilityLabel={opt.label}
      disabled={optDisabled}
      onPress={() => { onPick(opt.value); }}
      style={{ flexDirection: 'row', alignItems: 'center', gap: 10, opacity: optDisabled ? 0.5 : 1 }}
    >
      <View style={outer}>
        {isSel ? (
          <View style={{ width: size * 0.5, height: size * 0.5, borderRadius: size * 0.25, backgroundColor: head }} />
        ) : null}
      </View>
      <RNText style={{ color: head, fontSize: 15, fontFamily: 'Calibre-Medium' }}>{opt.label}</RNText>
    </Pressable>
  );
}

export function RadioGroup(props: RadioGroupProps): React.ReactElement {
  const {
    name,
    options = [],
    defaultValue,
    value: controlled,
    direction = 'col',
    disabled: groupDisabled,
    ariaLabel,
    onChange,
    size = 20,
    dark = false,
    style,
  } = props;

  const [internal, setInternal] = useState<string | undefined>(defaultValue);
  const selected = controlled ?? internal;

  const head = dark ? '#ffffff' : '#000000';
  const border = dark ? '#282a2d' : '#e4e4e5';

  function pick(v: string): void {
    if (controlled === undefined) setInternal(v);
    onChange?.(v);
  }

  return (
    <View
      accessibilityRole="radiogroup"
      accessibilityLabel={ariaLabel ?? name}
      style={[
        { flexDirection: direction === 'row' ? 'row' : 'column', gap: 12 },
        ...styleList(style),
      ]}
    >
      {options.map((opt) => (
        <RadioOptionRow
          key={opt.value}
          opt={opt}
          selected={selected}
          groupDisabled={groupDisabled ?? false}
          size={size}
          head={head}
          border={border}
          onPick={pick}
        />
      ))}
    </View>
  );
}

// packages/kit/src/vue/RadioGroup.vue
<script setup lang="ts">
import { computed } from 'vue';

export interface RadioOption {
  label: string;
  value: string;
  disabled?: boolean;
}

const props = withDefaults(
  defineProps<{
    name?: string;
    options?: RadioOption[];
    modelValue?: string;
    direction?: 'row' | 'col';
    disabled?: boolean;
    required?: boolean;
    ariaLabel?: string;
    size?: number;
    dark?: boolean;
  }>(),
  { options: () => [], direction: 'col', size: 20, dark: false },
);

const emit = defineEmits<{ 'update:modelValue': [value: string] }>();

const head = computed(() => (props.dark ? '#ffffff' : '#000000'));
const border = computed(() => (props.dark ? '#282a2d' : '#e4e4e5'));

const groupStyle = computed<Record<string, string>>(() => ({
  display: 'flex',
  flexDirection: props.direction === 'row' ? 'row' : 'column',
  gap: '12px',
}));

function isSelected(opt: RadioOption): boolean {
  return opt.value === props.modelValue;
}

function isDisabled(opt: RadioOption): boolean {
  return props.disabled || (opt.disabled ?? false);
}

function rowStyle(opt: RadioOption): Record<string, string> {
  return {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '10px',
    opacity: isDisabled(opt) ? '0.5' : '1',
    cursor: isDisabled(opt) ? 'default' : 'pointer',
    background: 'none',
    border: '0',
    padding: '0',
  };
}

function outerStyle(opt: RadioOption): Record<string, string> {
  return {
    width: `${props.size}px`,
    height: `${props.size}px`,
    borderRadius: `${props.size / 2}px`,
    borderWidth: '1.5px',
    borderStyle: 'solid',
    borderColor: isSelected(opt) ? head.value : border.value,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  };
}

const dotStyle = computed<Record<string, string>>(() => ({
  width: `${props.size * 0.5}px`,
  height: `${props.size * 0.5}px`,
  borderRadius: `${props.size * 0.25}px`,
  backgroundColor: head.value,
}));

const labelStyle = computed<Record<string, string>>(() => ({
  color: head.value,
  fontSize: '15px',
  fontFamily: 'Calibre-Medium',
}));

function pick(opt: RadioOption): void {
  if (isDisabled(opt)) return;
  emit('update:modelValue', opt.value);
}
</script>

<template>
  <div role="radiogroup" :aria-label="ariaLabel ?? name" :style="groupStyle">
    <button
      v-for="opt in options"
      :key="opt.value"
      type="button"
      role="radio"
      :aria-checked="isSelected(opt)"
      :aria-label="opt.label"
      :disabled="isDisabled(opt)"
      :style="rowStyle(opt)"
      @click="pick(opt)"
    >
      <span :style="outerStyle(opt)">
        <span v-if="isSelected(opt)" :style="dotStyle" />
      </span>
      <span :style="labelStyle">{{ opt.label }}</span>
    </button>
  </div>
</template>
