// packages/kit/src/react-native/video-player.tsx

import { Video, ResizeMode } from 'expo-av';
import { View } from 'react-native';

export interface VideoPlayerProps {
  src: string;
  poster?: string;
  controls?: boolean;
}

export function VideoPlayer(props: VideoPlayerProps): React.ReactElement {
  const { src, poster, controls = true } = props;
  return (
    <View
      style={{
        width: '100%',
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: '#000000',
      }}
    >
      <Video
        source={{ uri: src }}
        posterSource={poster ? { uri: poster } : undefined}
        usePoster={poster !== undefined}
        style={{ width: '100%', aspectRatio: 16 / 9 }}
        useNativeControls={controls}
        resizeMode={ResizeMode.CONTAIN}
        shouldPlay={false}
      />
    </View>
  );
}

// packages/kit/src/vue/VideoPlayer.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    src: string;
    poster?: string;
    controls?: boolean;
  }>(),
  { controls: true },
);
</script>

<template>
  <video
    :src="src"
    :poster="poster"
    :controls="controls"
    preload="metadata"
    :style="{
      width: '100%',
      aspectRatio: '16 / 9',
      borderRadius: '12px',
      backgroundColor: '#000000',
      display: 'block',
    }"
  />
</template>
