// packages/kit/src/react-native/view-host.tsx

import { useMemo } from 'react';
import { KitRenderer } from './kit-renderer';
import {
  payloadRegistry,
  type PayloadHandlers,
  type WidgetDataContext,
  type WidgetRoot,
} from '../kit';

export interface ViewHostProps {
  node: WidgetRoot;
  actions?: PayloadHandlers;
  data?: WidgetDataContext;
}

export function ViewHost({ node, actions, data }: ViewHostProps): React.ReactElement {
  const registry = useMemo(() => payloadRegistry(actions ?? {}), [actions]);
  return <KitRenderer node={node} registry={registry} data={data} />;
}

// packages/kit/src/vue/ViewHost.vue
<script setup lang="ts">
import { computed } from 'vue';
import KitRenderer from './KitRenderer.vue';
import {
  payloadRegistry,
  type PayloadHandlers,
  type WidgetDataContext,
  type WidgetRoot,
} from '../kit';

const props = defineProps<{
  node: WidgetRoot;
  actions?: PayloadHandlers;
  data?: WidgetDataContext;
}>();

const registry = computed(() => payloadRegistry(props.actions ?? {}));
</script>

<template>
  <KitRenderer :node="node" :registry="registry" :data="data" />
</template>
