// apps/stage/components/home/contacts.tsx

import { useEffect, useMemo, useState } from 'react';

import { isAddress } from 'viem';
import { Caption } from '@stage-labs/kit/react-native/caption';
import { Image } from '@stage-labs/kit/react-native/image';
import { ListView, ListViewItem } from '@stage-labs/kit/react-native/list-view';
import { Text } from '@stage-labs/kit/react-native/text';
import { useKitScheme } from '@stage-labs/kit/react-native/theme-context';
import { Box, Row, Col } from '../layout';
import { EmptyState } from '../chrome/EmptyState';
import { shortAddress } from '../../modules/messaging';
import { resolveHandleToAddress } from '../../lib/resolveHandle';
import { usePeerProfiles, getPeerName } from '../../lib/peerProfiles';
import { peerAvatarUrl } from '../../lib/peerProfiles';
import { peopleLookup } from './contacts.model';
import { homeRows } from './state';

function getExistingPeers(): { address: string; convId: string }[] {
  const seen = new Set<string>();
  const peers: { address: string; convId: string }[] = [];
  for (const { peerAddress: a, convId: cid } of homeRows() ?? []) {
    if (!a || !cid) continue;
    const k = a.toLowerCase();
    if (seen.has(k)) continue;
    seen.add(k);
    peers.push({ address: a, convId: cid });
  }
  return peers;
}

const LOOKUP_DEBOUNCE_MS = 300;
const NO_MATCH_HINT = 'No matches. Try a username, a full address or a name.eth to start a chat.';

function ContactResultRow({ title, subtitle, address, dark, onPress }: {
  title: string; subtitle?: string; address: string; dark: boolean; onPress: () => void;
}): React.ReactElement {
  return (
    <ListViewItem dark={dark} align="center" gap={12} onPress={onPress}>
      <Row align="center" gap={12} flex={1}>
        <Image src={peerAvatarUrl(address, 40)} size={40} radius="full" />
        <Col gap={2} flex={1}>
          <Text value={title} weight="semibold" truncate />
          {subtitle === undefined || subtitle === '' ? null : (
            <Caption value={subtitle} color="secondary" truncate />
          )}
        </Col>
      </Row>
    </ListViewItem>
  );
}

interface ResolvedPeer { address: string; title: string }

function useResolvedPeer(q: string, enabled: boolean): ResolvedPeer | null {
  const [resolved, setResolved] = useState<ResolvedPeer | null>(null);
  const lookup = useMemo(() => (enabled ? peopleLookup(q) : null), [q, enabled]);
  useEffect(() => {
    if (!lookup) { setResolved(null); return; }
    if (isAddress(lookup.handle)) { setResolved({ address: lookup.handle, title: lookup.title }); return; }
    let cancelled = false;
    setResolved(null);
    const t = setTimeout(() => {
      void resolveHandleToAddress(lookup.handle).then((addr) => {
        if (!cancelled && addr) setResolved({ address: addr.toLowerCase(), title: lookup.title });
      });
    }, LOOKUP_DEBOUNCE_MS);
    return () => { cancelled = true; clearTimeout(t); };
  }, [lookup?.handle, enabled]);
  return resolved;
}

export function HomeContactResults(
  { query, noChannels }: { query: string; noChannels: boolean },
): React.ReactElement | null {
  const q = query.trim();
  const dark = useKitScheme() === 'dark';
  const existing = useMemo(() => getExistingPeers(), []);

  const filtered = useMemo(() => {
    const needle = q.toLowerCase();
    if (!needle) return [];
    return existing.filter(p => {
      if (p.address.toLowerCase().includes(needle)) return true;
      const n = getPeerName(p.address);
      return !!n && n.toLowerCase().includes(needle);
    });
  }, [existing, q]);

  const resolved = useResolvedPeer(q, filtered.length === 0);
  usePeerProfiles([resolved?.address, ...existing.map(p => p.address)]);

  const open = (address: string, convId?: string): void => {
    const target = isAddress(address) ? address : (convId ?? address);
    void import('expo-router').then(({ router }) => {
      router.push({ pathname: '/[convId]', params: { convId: target } });
    });
  };

  const showResolved = resolved && !filtered.some(p => p.address.toLowerCase() === resolved.address);
  if (!q) return null;
  if (!showResolved && filtered.length === 0) {
    if (!noChannels) return null;
    return <EmptyState title={NO_MATCH_HINT} />;
  }

  const rows = [
    ...(showResolved
      ? [{
          address: resolved.address,
          convId: undefined,
          title: getPeerName(resolved.address) ?? (resolved.title === '' ? shortAddress(resolved.address) : resolved.title),
          subtitle: 'Start chat',
        }]
      : []),
    ...filtered.map(p => ({
      address: p.address,
      convId: p.convId,
      title: getPeerName(p.address) ?? shortAddress(p.address),
      subtitle: getPeerName(p.address) ? shortAddress(p.address) : undefined,
    })),
  ];

  return (
    <Box>
      <Box padding={{ x: 16, top: 16, bottom: 6 }}>
        <Caption value="PEOPLE" color="secondary" weight="semibold" />
      </Box>
      <ListView dark={dark}>
        {rows.map((r) => (
          <ContactResultRow
            key={`${r.address}-${r.convId ?? ''}`}
            title={r.title}
            subtitle={r.subtitle}
            address={r.address}
            dark={dark}
            onPress={() => { open(r.address, r.convId); }}
          />
        ))}
      </ListView>
    </Box>
  );
}

// apps/ui/src/views/Contacts.vue
<script setup lang="ts">

import {
  getOrCreateXmtpClient, peerEthAddressOfDm, shortAddress, stampAvatarUrl,
} from '../lib/xmtp';
import { useSearchResolution } from '../lib/useSearchResolution';
import { readProfile, loadCachedProfile } from '../lib/profile';
import { useEffectiveScheme } from '@/lib/kitTheme';
import KitRenderer from '@stage-labs/kit/vue/kit-renderer';
import type { ListViewNode, WidgetActionRegistry } from '@stage-labs/kit/kit';
import { contactRow, CONTACT_PRESS } from '@stage-labs/views';

const scheme = useEffectiveScheme();

interface Contact { address: string; convId: string }

const router = useRouter();
const contacts = ref<Contact[] | null>(null);
const error = ref<string>('');
const query = ref<string>('');
const { searchResolution, openSearchedProfile } = useSearchResolution(query, router);

const peerNames = ref<Record<string, string>>({});
function peerName(address: string): string | null {
  return peerNames.value[address.toLowerCase()] ?? null;
}
function resolvePeerName(address: string): void {
  const lower = address.toLowerCase();
  if (peerNames.value[lower]) return;
  const cached = loadCachedProfile(address)?.name;
  if (cached) peerNames.value = { ...peerNames.value, [lower]: cached };
  void readProfile(address).then((p) => {
    if (p?.name) peerNames.value = { ...peerNames.value, [lower]: p.name };
  });
}

const filtered = computed(() => {
  if (!contacts.value) return null;
  const q = query.value.trim().toLowerCase();
  if (!q) return contacts.value;
  return contacts.value.filter(c => c.address.toLowerCase().includes(q));
});

onMounted(async () => {
  try {
    const client = await getOrCreateXmtpClient('production');
    await client.conversations.syncAll();
    const convs = await client.conversations.list();
    const resolved = await Promise.all(convs.map(async c => {
      const addr = await peerEthAddressOfDm(c);
      return addr ? { address: addr, convId: c.id } : null;
    }));
    const seen = new Set<string>();
    const dedup: Contact[] = [];
    for (const r of resolved) {
      if (!r) continue;
      const key = r.address.toLowerCase();
      if (seen.has(key)) continue;
      seen.add(key);
      dedup.push(r);
    }
    dedup.sort((a, b) => a.address.localeCompare(b.address));
    contacts.value = dedup;
    for (const c of dedup) resolvePeerName(c.address);
  } catch (e) { error.value = (e as Error).message; }
});

const listNode = computed<ListViewNode>(() => ({
  type: 'ListView',
  children: (filtered.value ?? contacts.value ?? []).map(c =>
    contactRow({
      name: peerName(c.address) ?? c.address,
      avatarUri: stampAvatarUrl(c.address, 80),
      handle: peerName(c.address) ? shortAddress(c.address) : undefined,
      payload: { convId: c.convId },
    }),
  ),
}));

const registry: WidgetActionRegistry = {
  [CONTACT_PRESS]: (action) => {
    const convId = action.payload.convId;
    if (typeof convId === 'string') void router.push(`/xmtp/${convId}`);
  },
};
</script>

<template>
  <Col class="min-h-screen">
    <Row align="center" :gap="4" class="h-[52px] box-border shrink-0 pl-2 pr-1">
      <AccountSwitcher />
      <Text size="4xl" weight="semibold" class="flex-1 pl-2 text-metro-head-light dark:text-metro-head-dark">
        Contacts
      </Text>
    </Row>
    <Col class="px-3 pb-2">
      <Input
        v-model="query"
        :dark="scheme === 'dark'"
        placeholder="Search contacts or paste 0x… / name.eth…"
        autocomplete="off"
        autocorrect="off"
        autocapitalize="off"
        class="w-full bg-metro-surface-light dark:bg-metro-surface-dark
          border border-metro-border-light dark:border-metro-border-dark rounded-lg px-3 py-2 text-sm
          text-metro-fg-light dark:text-metro-fg-dark outline-none
          placeholder:text-metro-sub-light dark:placeholder:text-metro-sub-dark"
      />
    </Col>
    <SearchResolution
      :status="searchResolution.status"
      :address="searchResolution.address"
      :query="query"
      @open="openSearchedProfile"
    />
    <Col v-if="error" align="center" justify="center" class="flex-1 text-sm text-metro-fg-light dark:text-metro-fg-dark px-6">
      {{ error }}
    </Col>
    <Col v-else-if="!contacts" align="center" justify="center" class="flex-1 text-xs text-metro-sub-light dark:text-metro-sub-dark">
      Loading contacts…
    </Col>
    <Col v-else class="flex-1">
      <Col v-if="filtered && filtered.length === 0" class="p-8 text-center text-sm text-metro-sub-light dark:text-metro-sub-dark">
        {{ query ? `No matches for "${query}"` : 'No contacts yet. Start a DM from Channels to populate this list.' }}
      </Col>
      <KitRenderer v-else :node="listNode" :registry="registry" />
    </Col>
  </Col>
</template>
