// packages/kit/src/vue/AvatarView.vue
<script setup lang="ts">
import { computed } from 'vue';
import Image from './Image.vue';
import { AVATAR_SIZES, type AvatarSize } from '../avatar';

const props = withDefaults(
  defineProps<{
    src?: string | null;
    size?: AvatarSize | number;
    square?: boolean;
    alt?: string;
    placeholderColor?: string;
  }>(),
  { size: 'md', placeholderColor: '#282a2d' },
);

const px = computed(() => (typeof props.size === 'number' ? props.size : AVATAR_SIZES[props.size]));

const radius = computed(() => (props.square ? Math.round(px.value * 0.12) : 999));

const hasSrc = computed(() => Boolean(props.src?.trim()));

const boxStyle = computed<Record<string, string>>(() => ({
  width: `${px.value}px`,
  height: `${px.value}px`,
  borderRadius: `${radius.value}px`,
  backgroundColor: props.placeholderColor,
}));
</script>

<template>
  <Image
    v-if="hasSrc"
    :src="src as string"
    :alt="alt"
    :size="px"
    :radius="radius"
    :background="placeholderColor"
  />
  <div v-else :style="boxStyle" />
</template>

// packages/kit/src/react-native/avatar.view.tsx

import { View } from 'react-native';
import { Image } from './image';
import { AVATAR_SIZES, type AvatarSize } from '../avatar';
import type { ImageStyle, StyleProp } from 'react-native';

export interface AvatarViewProps {
  src?: string | null;
  size?: AvatarSize | number;
  square?: boolean;
  alt?: string;
  placeholderColor?: string;
  style?: StyleProp<ImageStyle>;
}

export function AvatarView(props: AvatarViewProps): React.ReactElement {
  const { src, size = 'md', square, alt, placeholderColor = '#282a2d', style } = props;
  const px = typeof size === 'number' ? size : AVATAR_SIZES[size];
  const baseStyle: StyleProp<ImageStyle> = {
    width: px,
    height: px,
    borderRadius: square ? Math.round(px * 0.12) : 999,
    backgroundColor: placeholderColor,
  };

  if (src?.trim()) {
    return <Image src={src} alt={alt} style={[baseStyle, style] as ImageStyle[]} />;
  }
  return <View style={[baseStyle, style]} />;
}
