// packages/kit/src/vue/Button.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  legacyVariantToColor,
  resolveColors,
  SIZES,
  type ButtonColor,
  type ButtonControlVariant,
  type ButtonSize,
  type ButtonVariant,
  type VariantColors,
} from '../button.styles';

export type {
  ButtonColor,
  ButtonControlVariant,
  ButtonSize,
  ButtonVariant,
} from '../button.styles';

const props = withDefaults(
  defineProps<{
    color?: ButtonColor;
    variant?: ButtonControlVariant | ButtonVariant;
    styleColor?: 'primary' | 'secondary';
    size?: ButtonSize;
    label?: string;
    disabled?: boolean;
    loading?: boolean;
    block?: boolean;
    fullWidth?: boolean;
    pill?: boolean;
    uniform?: boolean;
    dark?: boolean;
    tintBg?: string;
    tintFg?: string;
    radius?: number;
  }>(),
  { size: 'md', disabled: false, loading: false, dark: false },
);

const emit = defineEmits<{ click: [event: MouseEvent] }>();

const LEGACY_VARIANTS = new Set<ButtonVariant>(['primary', 'secondary', 'danger']);
const DEFAULT_RADIUS = 999;

function resolveModel(
  color: ButtonColor | undefined,
  variant: ButtonControlVariant | ButtonVariant | undefined,
  styleColor: 'primary' | 'secondary' | undefined,
): { color: ButtonColor; variant: ButtonControlVariant } {
  if (variant && LEGACY_VARIANTS.has(variant as ButtonVariant) && !color) {
    return legacyVariantToColor(variant as ButtonVariant);
  }
  const baseColor: ButtonColor = color ?? styleColor ?? 'primary';
  const treatment: ButtonControlVariant =
    variant && (['solid', 'soft', 'outline', 'ghost'] as string[]).includes(variant)
      ? (variant as ButtonControlVariant)
      : 'solid';
  return { color: baseColor, variant: treatment };
}

const colors = computed<VariantColors>(() => {
  const model = resolveModel(props.color, props.variant, props.styleColor);
  const base = resolveColors(model.color, model.variant, props.dark);
  return { ...base, bg: props.tintBg ?? base.bg, text: props.tintFg ?? base.text };
});

const stretch = computed(() => props.block || props.fullWidth);
const square = computed(() => props.pill || props.uniform);
const isDisabled = computed(() => props.disabled || props.loading);
const spec = computed(() => SIZES[props.size]);

const style = computed<Record<string, string>>(() => {
  const c = colors.value;
  const s = spec.value;
  const css: Record<string, string> = {
    height: `${s.height}px`,
    paddingLeft: square.value ? '0' : `${s.paddingHorizontal}px`,
    paddingRight: square.value ? '0' : `${s.paddingHorizontal}px`,
    borderRadius: `${props.radius ?? DEFAULT_RADIUS}px`,
    display: 'inline-flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: `${s.gap}px`,
    backgroundColor: c.bg,
    color: c.text,
    fontSize: `${s.fontSize}px`,
    fontFamily: 'Calibre-Semibold',
    fontWeight: '600',
    borderWidth: c.borderColor ? '1px' : '0',
    borderStyle: 'solid',
    borderColor: c.borderColor ?? 'transparent',
    cursor: isDisabled.value ? 'default' : 'pointer',
    opacity: isDisabled.value ? '0.4' : '1',
  };
  if (square.value) css.width = `${s.height}px`;
  else if (stretch.value) css.width = '100%';
  return css;
});

function onClick(event: MouseEvent): void {
  if (isDisabled.value) return;
  emit('click', event);
}
</script>

<template>
  <button type="button" :style="style" :disabled="isDisabled" @click="onClick">
    <slot name="iconStart" />
    <slot>{{ label }}</slot>
    <slot name="iconEnd" />
  </button>
</template>

// packages/kit/src/react-native/button.tsx

import { useMemo, type ReactNode } from 'react';
import {
  ActivityIndicator,
  Pressable,
  Text,
  type PressableProps,
  type TextStyle,
  type ViewStyle,
} from 'react-native';
import {
  legacyVariantToColor,
  resolveColors,
  SIZES,
  textLabelStyle,
  type ButtonColor,
  type ButtonControlVariant,
  type ButtonSize,
  type ButtonVariant,
} from '../button.styles';

export type {
  ButtonColor,
  ButtonControlVariant,
  ButtonSize,
  ButtonVariant,
} from '../button.styles';

const LEGACY_VARIANTS = new Set<ButtonVariant>(['primary', 'secondary', 'danger']);

let defaultButtonRadius = 999;
export function setDefaultButtonRadius(r: number): void {
  if (Number.isFinite(r) && r >= 0) defaultButtonRadius = r;
}
export function getDefaultButtonRadius(): number {
  return defaultButtonRadius;
}

export interface ButtonProps
  extends Omit<PressableProps, 'children' | 'style' | 'disabled'> {
  color?: ButtonColor;
  variant?: ButtonControlVariant | ButtonVariant;
  style?: ViewStyle;
  styleColor?: 'primary' | 'secondary';
  size?: ButtonSize;
  label?: string;
  children?: ReactNode;
  disabled?: boolean;
  loading?: boolean;
  block?: boolean;
  fullWidth?: boolean;
  pill?: boolean;
  uniform?: boolean;
  iconStart?: ReactNode;
  iconEnd?: ReactNode;
  icon?: ReactNode;
  iconRight?: ReactNode;
  dark?: boolean;
  tintBg?: string;
  tintFg?: string;
  radius?: number;
  textStyle?: TextStyle;
}

function resolveModel(
  color: ButtonColor | undefined,
  variant: ButtonControlVariant | ButtonVariant | undefined,
  styleColor: 'primary' | 'secondary' | undefined,
): { color: ButtonColor; variant: ButtonControlVariant } {
  if (variant && LEGACY_VARIANTS.has(variant as ButtonVariant) && !color) {
    return legacyVariantToColor(variant as ButtonVariant);
  }
  const baseColor: ButtonColor = color ?? styleColor ?? 'primary';
  const treatment: ButtonControlVariant =
    variant && (['solid', 'soft', 'outline', 'ghost'] as string[]).includes(variant)
      ? (variant as ButtonControlVariant)
      : 'solid';
  return { color: baseColor, variant: treatment };
}

type ResolvedColors = ReturnType<typeof resolveColors>;

interface ContainerStyleArgs {
  spec: (typeof SIZES)[ButtonSize];
  square: boolean;
  stretch: boolean;
  radius: number | undefined;
  c: ResolvedColors;
  isDisabled: boolean;
  style: ViewStyle | undefined;
}

function pickBackground(c: ResolvedColors, usePressedBg: boolean): string {
  if (usePressedBg && c.pressedBg) return c.pressedBg;
  if (usePressedBg && c.ghostPressedBg) return c.ghostPressedBg;
  return c.bg;
}

function pickOpacity(c: ResolvedColors, usePressedBg: boolean, isDisabled: boolean): number {
  if (isDisabled) return 0.4;
  if (usePressedBg && !c.pressedBg && !c.ghostPressedBg) return 0.85;
  return 1;
}

function containerStyle(
  args: ContainerStyleArgs,
  pressed: boolean,
): (ViewStyle | undefined)[] {
  const { spec, square, stretch, radius, c, isDisabled, style } = args;
  const usePressedBg = pressed && !isDisabled;
  const base: ViewStyle = {
    height: spec.height,
    width: square ? spec.height : stretch ? '100%' : undefined,
    paddingHorizontal: square ? 0 : spec.paddingHorizontal,
    borderRadius: radius ?? defaultButtonRadius,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spec.gap,
    backgroundColor: pickBackground(c, usePressedBg),
    borderWidth: c.borderColor ? 1 : 0,
    borderColor: c.borderColor,
    alignSelf: stretch && !square ? 'stretch' : 'flex-start',
    opacity: pickOpacity(c, usePressedBg, isDisabled),
  };
  return [base, style];
}

function renderLabel(
  children: ReactNode,
  label: string | undefined,
  spec: (typeof SIZES)[ButtonSize],
  textColor: string,
  textStyle: TextStyle | undefined,
): ReactNode {
  if (children !== undefined) {
    if (typeof children !== 'string') return children;
    return (
      <Text style={[textLabelStyle(spec, textColor), textStyle]} numberOfLines={1}>
        {children}
      </Text>
    );
  }
  if (label !== undefined) {
    return (
      <Text style={[textLabelStyle(spec, textColor), textStyle]} numberOfLines={1}>
        {label}
      </Text>
    );
  }
  return null;
}

interface TintArgs {
  color: ButtonColor | undefined;
  variant: ButtonControlVariant | ButtonVariant | undefined;
  styleColor: 'primary' | 'secondary' | undefined;
  dark: boolean;
  tintBg: string | undefined;
  tintFg: string | undefined;
}

function useResolvedColors(t: TintArgs): ResolvedColors {
  return useMemo(() => {
    const model = resolveModel(t.color, t.variant, t.styleColor);
    const base = resolveColors(model.color, model.variant, t.dark);
    return { ...base, bg: t.tintBg ?? base.bg, text: t.tintFg ?? base.text };
  }, [t.color, t.variant, t.styleColor, t.dark, t.tintBg, t.tintFg]);
}

function orFlag(a: boolean | undefined, b: boolean | undefined): boolean {
  return a === true || b === true;
}

export function Button(props: ButtonProps): React.ReactElement {
  const {
    color,
    variant,
    styleColor,
    block,
    fullWidth,
    pill,
    uniform,
    dark = false,
    tintBg,
    tintFg,
    size = 'md',
    label,
    children,
    disabled = false,
    loading = false,
    iconStart,
    iconEnd,
    icon,
    iconRight,
    radius,
    style,
    textStyle,
    ...rest
  } = props;

  const startIcon = iconStart ?? icon;
  const endIcon = iconEnd ?? iconRight;
  const stretch = orFlag(block, fullWidth);
  const square = orFlag(pill, uniform);

  const spec = SIZES[size];
  const c = useResolvedColors({ color, variant, styleColor, dark, tintBg, tintFg });
  const isDisabled = disabled || loading;

  const labelNode = renderLabel(children, label, spec, c.text, textStyle);
  const styleArgs: ContainerStyleArgs = { spec, square, stretch, radius, c, isDisabled, style };

  return (
    <Pressable
      accessibilityRole="button"
      accessibilityState={{ disabled: isDisabled, busy: loading }}
      disabled={isDisabled}
      style={({ pressed }: { pressed: boolean }) => containerStyle(styleArgs, pressed)}
      {...rest}
    >
      {loading ? (
        <ActivityIndicator size={spec.spinner} color={c.text} />
      ) : (
        <>
          {startIcon}
          {labelNode}
          {endIcon}
        </>
      )}
    </Pressable>
  );
}
