// packages/kit/src/vue/Form.vue
<script setup lang="ts">
import Box from './Box.vue';
import type { BoxBaseProps } from '../layout';
import type { Surface } from './Box.vue';

withDefaults(
  defineProps<
    Omit<BoxBaseProps, 'direction'> & {
      direction?: 'row' | 'col';
      surface?: Surface;
    }
  >(),
  { direction: 'col', gap: 12 },
);

const emit = defineEmits<{ submit: [] }>();

function onSubmit(event: Event): void {
  event.preventDefault();
  emit('submit');
}
</script>

<template>
  <Box tag="form" :direction="direction" v-bind="$props" @submit="onSubmit">
    <slot />
  </Box>
</template>

// packages/kit/src/react-native/form.tsx

import { createContext, useContext, type ReactNode } from 'react';
import { Box, type BoxProps } from './box';

interface FormContextValue {
  submit: () => void;
}

const FormContext = createContext<FormContextValue>({
  submit: () => undefined,
});

export function useFormSubmit(): () => void {
  return useContext(FormContext).submit;
}

export interface FormProps extends Omit<BoxProps, 'direction'> {
  direction?: 'row' | 'col';
  onSubmit?: () => void;
  children?: ReactNode;
}

export function Form(props: FormProps): React.ReactElement {
  const { direction = 'col', onSubmit, children, gap = 12, ...rest } = props;
  const submit = (): void => {
    onSubmit?.();
  };
  return (
    <FormContext.Provider value={{ submit }}>
      <Box direction={direction} gap={gap} {...rest}>
        {children}
      </Box>
    </FormContext.Provider>
  );
}
