// packages/kit/src/vue/Input.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import {
  controlBoxStyle,
  controlColors,
  controlTextStyle,
  type ControlSize,
  type ControlVariant,
} from '../control.styles';
import { BLOCK_RADIUS_DEFAULT } from '../tokens';

export type InputType = 'text' | 'email' | 'password' | 'number' | 'tel' | 'url';

const props = withDefaults(
  defineProps<{
    name?: string;
    modelValue?: string;
    placeholder?: string;
    variant?: ControlVariant;
    size?: ControlSize;
    pill?: boolean;
    disabled?: boolean;
    inputType?: InputType;
    autoFocus?: boolean;
    radius?: number;
    dark?: boolean;
  }>(),
  { variant: 'soft', size: 'md', inputType: 'text', dark: false },
);

const emit = defineEmits<{
  'update:modelValue': [value: string];
  submit: [value: string];
}>();

const focused = ref(false);

const colors = computed(() => controlColors(props.variant, props.dark));
const corner = computed(() => props.radius ?? (props.pill ? 999 : BLOCK_RADIUS_DEFAULT));

function toCss(entries: Record<string, string | number>): Record<string, string> {
  const css: Record<string, string> = {};
  for (const [k, v] of Object.entries(entries)) {
    css[k] = typeof v === 'number' ? `${v}px` : v;
  }
  return css;
}

const style = computed<Record<string, string>>(() => {
  const box = controlBoxStyle(props.size, props.variant, colors.value, corner.value, focused.value);
  const text = controlTextStyle(props.size, colors.value);
  const css = { ...toCss(box as Record<string, string | number>), ...toCss(text as Record<string, string | number>) };
  css.borderStyle = 'solid';
  css.outline = 'none';
  css.width = '100%';
  css.fontFamily = 'Calibre-Medium';
  if (props.disabled) css.opacity = '0.5';
  return css;
});

function onInput(event: Event): void {
  emit('update:modelValue', (event.target as HTMLInputElement).value);
}

function onKeydown(event: KeyboardEvent): void {
  if (event.key === 'Enter') emit('submit', (event.target as HTMLInputElement).value);
}

const nativeType = computed(() => (props.inputType === 'number' ? 'number' : props.inputType));
</script>

<template>
  <input
    :name="name"
    :type="nativeType"
    :value="modelValue"
    :placeholder="placeholder"
    :disabled="disabled"
    :autofocus="autoFocus"
    :style="style"
    @input="onInput"
    @keydown="onKeydown"
    @focus="focused = true"
    @blur="focused = false"
  />
</template>

// packages/kit/src/react-native/input.tsx

import { forwardRef, useState } from 'react';
import {
  TextInput,
  type TextInputProps,
  type KeyboardTypeOptions,
  type StyleProp,
  type TextStyle,
} from 'react-native';
import {
  chainFocus,
  controlBoxStyle,
  controlColors,
  controlTextStyle,
  fieldIds,
  type ControlSize,
  type ControlVariant,
} from '../control.styles';
import { BLOCK_RADIUS_DEFAULT } from '../tokens';

export type InputType = 'text' | 'email' | 'password' | 'number' | 'tel' | 'url';

const KEYBOARD: Record<InputType, KeyboardTypeOptions> = {
  text: 'default',
  email: 'email-address',
  password: 'default',
  number: 'numeric',
  tel: 'phone-pad',
  url: 'url',
};

export interface InputProps {
  name?: string;
  defaultValue?: string;
  value?: string;
  placeholder?: string;
  variant?: ControlVariant;
  size?: ControlSize;
  pill?: boolean;
  disabled?: boolean;
  inputType?: InputType;
  autoFocus?: boolean;
  autoSelect?: boolean;
  required?: boolean;
  pattern?: string;
  radius?: number;
  onChangeText?: (text: string) => void;
  onSubmit?: (text: string) => void;
  dark?: boolean;
  placeholderTextColor?: string;
  style?: StyleProp<TextStyle>;
  inputProps?: Omit<
    TextInputProps,
    'value' | 'defaultValue' | 'onChangeText' | 'style' | 'placeholder' | 'editable'
  >;
}

export const Input = forwardRef<TextInput, InputProps>(function Input(props, ref) {
  const {
    name,
    defaultValue,
    value,
    placeholder,
    variant = 'soft',
    size = 'md',
    pill,
    disabled,
    inputType = 'text',
    autoFocus,
    autoSelect,
    radius,
    onChangeText,
    onSubmit,
    dark = false,
    placeholderTextColor,
    style,
    inputProps,
  } = props;

  const [focused, setFocused] = useState(false);
  const colors = controlColors(variant, dark);
  const corner = radius ?? (pill ? 999 : BLOCK_RADIUS_DEFAULT);
  const box = controlBoxStyle(size, variant, colors, corner, focused);
  const text = controlTextStyle(size, colors);

  return (
    <TextInput
      {...inputProps}
      ref={ref}
      {...fieldIds(name)}
      value={value}
      defaultValue={defaultValue}
      placeholder={placeholder}
      placeholderTextColor={placeholderTextColor ?? colors.placeholder}
      editable={!disabled}
      autoFocus={autoFocus}
      selectTextOnFocus={autoSelect}
      keyboardType={KEYBOARD[inputType]}
      secureTextEntry={inputType === 'password'}
      onChangeText={onChangeText}
      onSubmitEditing={(e) => {
        onSubmit?.(e.nativeEvent.text);
        inputProps?.onSubmitEditing?.(e);
      }}
      onFocus={(e) => { chainFocus(true, setFocused, inputProps?.onFocus, e); }}
      onBlur={(e) => { chainFocus(false, setFocused, inputProps?.onBlur, e); }}
      style={[box, text, disabled && { opacity: 0.5 }, style]}
    />
  );
});
