// packages/kit/src/vue/Label.vue
<script setup lang="ts">
import { computed } from 'vue';

export type LabelSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
export type LabelWeight = 'normal' | 'medium' | 'semibold' | 'bold';
export type LabelAlign = 'start' | 'center' | 'end';

const SIZE: Record<LabelSize, number> = { xs: 12, sm: 13, md: 15, lg: 17, xl: 20 };
const FONT: Record<LabelWeight, string> = {
  normal: 'Calibre-Medium',
  medium: 'Calibre-Medium',
  semibold: 'Calibre-Semibold',
  bold: 'Calibre-Semibold',
};
const ALIGN: Record<LabelAlign, string> = {
  start: 'left',
  center: 'center',
  end: 'right',
};

const props = withDefaults(
  defineProps<{
    value?: string;
    fieldName?: string;
    size?: LabelSize;
    weight?: LabelWeight;
    textAlign?: LabelAlign;
    color?: string;
    dark?: boolean;
  }>(),
  { size: 'md', weight: 'medium', textAlign: 'start', dark: false },
);

function headColor(dark: boolean): string {
  return dark ? '#ffffff' : '#000000';
}

const labelId = computed(() => (props.fieldName ? `label-${props.fieldName}` : undefined));

const style = computed<Record<string, string>>(() => ({
  color: props.color ?? headColor(props.dark),
  fontSize: `${SIZE[props.size]}px`,
  fontFamily: FONT[props.weight],
  textAlign: ALIGN[props.textAlign],
}));
</script>

<template>
  <label :id="labelId" :style="style"><slot>{{ value }}</slot></label>
</template>

// packages/kit/src/react-native/label.tsx

import { Text as RNText, type TextStyle } from 'react-native';
import { type ReactNode } from 'react';

export type LabelSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
export type LabelWeight = 'normal' | 'medium' | 'semibold' | 'bold';
export type LabelAlign = 'start' | 'center' | 'end';

const SIZE: Record<LabelSize, number> = { xs: 12, sm: 13, md: 15, lg: 17, xl: 20 };
const FONT: Record<LabelWeight, string> = {
  normal: 'Calibre-Medium',
  medium: 'Calibre-Medium',
  semibold: 'Calibre-Semibold',
  bold: 'Calibre-Semibold',
};
const ALIGN: Record<LabelAlign, TextStyle['textAlign']> = {
  start: 'left',
  center: 'center',
  end: 'right',
};

export interface LabelProps {
  value?: string;
  children?: ReactNode;
  fieldName?: string;
  size?: LabelSize;
  weight?: LabelWeight;
  textAlign?: LabelAlign;
  color?: string;
  dark?: boolean;
  style?: TextStyle | TextStyle[];
}

function headColor(dark: boolean): string {
  return dark ? '#ffffff' : '#000000';
}

export function Label(props: LabelProps): React.ReactElement {
  const {
    value,
    children,
    fieldName,
    size = 'md',
    weight = 'medium',
    textAlign = 'start',
    color,
    dark = false,
    style,
  } = props;

  const base: TextStyle = {
    color: color ?? headColor(dark),
    fontSize: SIZE[size],
    fontFamily: FONT[weight],
    textAlign: ALIGN[textAlign],
  };

  return (
    <RNText
      nativeID={fieldName ? `label-${fieldName}` : undefined}
      style={style ? [base, ...(Array.isArray(style) ? style : [style])] : base}
    >
      {value ?? children}
    </RNText>
  );
}
