// packages/kit/src/vue/QRCode.vue
<script setup lang="ts">
import { computed } from 'vue';
import { buildQrMatrix } from '../kit';

const props = withDefaults(
  defineProps<{
    value: string;
    size?: number;
    color?: string;
    background?: string;
  }>(),
  { size: 160, color: '#000000', background: '#ffffff' },
);

const matrix = computed(() => buildQrMatrix(props.value, props.size));
</script>

<template>
  <svg :width="size" :height="size" :style="{ display: 'block' }">
    <rect :x="0" :y="0" :width="size" :height="size" :fill="background" />
    <path :d="matrix.path" :fill="color" />
  </svg>
</template>

// packages/kit/src/react-native/qr-code.tsx

import { View } from 'react-native';
import Svg, { Path, Rect } from 'react-native-svg';
import { buildQrMatrix } from '../kit/qr';

export interface QrCodeProps {
  value: string;
  size?: number;
  color?: string;
  background?: string;
}

export function QrCode(props: QrCodeProps): React.ReactElement {
  const { value, size = 160, color = '#000000', background = '#ffffff' } = props;
  const matrix = buildQrMatrix(value, size);
  return (
    <View style={{ width: size, height: size }}>
      <Svg width={size} height={size}>
        <Rect x={0} y={0} width={size} height={size} fill={background} />
        <Path d={matrix.path} fill={color} />
      </Svg>
    </View>
  );
}
