// packages/kit/src/vue/Select.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import {
  controlBoxStyle,
  controlColors,
  type ControlSize,
  type ControlVariant,
} from '../control.styles';
import { BLOCK_RADIUS_DEFAULT, FONT_SIZE, schemePalette } from '../tokens';
import Icon from './Icon.vue';

export interface SelectOption {
  label: string;
  value: string;
}

const props = withDefaults(
  defineProps<{
    name?: string;
    options?: SelectOption[];
    modelValue?: string;
    placeholder?: string;
    variant?: ControlVariant;
    size?: ControlSize;
    pill?: boolean;
    block?: boolean;
    clearable?: boolean;
    disabled?: boolean;
    radius?: number;
    dark?: boolean;
  }>(),
  {
    options: () => [],
    placeholder: 'Select...',
    variant: 'soft',
    size: 'md',
    dark: false,
  },
);

const emit = defineEmits<{ 'update:modelValue': [value: string] }>();

const open = ref(false);

const colors = computed(() => controlColors(props.variant, props.dark));
const corner = computed(() => props.radius ?? (props.pill ? 999 : BLOCK_RADIUS_DEFAULT));
const p = computed(() => schemePalette(props.dark));
const sheetBg = computed(() => (props.dark ? '#1b1c1e' : '#ffffff'));

const current = computed(() => props.options.find((o) => o.value === props.modelValue));

function toCss(entries: Record<string, string | number>): Record<string, string> {
  const css: Record<string, string> = {};
  for (const [k, v] of Object.entries(entries)) {
    css[k] = typeof v === 'number' ? `${v}px` : v;
  }
  return css;
}

const triggerStyle = computed<Record<string, string>>(() => {
  const box = controlBoxStyle(props.size, props.variant, colors.value, corner.value, false);
  return {
    ...toCss(box as Record<string, string | number>),
    borderStyle: 'solid',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '8px',
    width: props.block ? '100%' : 'auto',
    alignSelf: props.block ? 'stretch' : 'flex-start',
    opacity: props.disabled ? '0.5' : '1',
    cursor: props.disabled ? 'default' : 'pointer',
  };
});

const labelStyle = computed<Record<string, string>>(() => ({
  flex: '1',
  color: current.value ? p.value.head : colors.value.placeholder,
  fontSize: `${FONT_SIZE.md}px`,
  fontFamily: 'Calibre-Medium',
  textAlign: 'left',
  whiteSpace: 'nowrap',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
}));

const panelStyle = computed<Record<string, string>>(() => ({
  position: 'absolute',
  top: 'calc(100% + 4px)',
  left: '0',
  right: '0',
  zIndex: '50',
  backgroundColor: sheetBg.value,
  borderRadius: '14px',
  borderWidth: '1px',
  borderStyle: 'solid',
  borderColor: p.value.border,
  overflow: 'hidden',
  maxHeight: '320px',
  overflowY: 'auto',
  boxShadow: '0 8px 24px rgba(0,0,0,0.18)',
}));

function rowStyle(opt: SelectOption): Record<string, string> {
  return {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '10px',
    paddingLeft: '16px',
    paddingRight: '16px',
    paddingTop: '13px',
    paddingBottom: '13px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: p.value.border,
    width: '100%',
    background: opt.value === props.modelValue ? p.value.pressed : 'transparent',
    border: '0',
    cursor: 'pointer',
  };
}

const rowLabelStyle = computed<Record<string, string>>(() => ({
  flex: '1',
  color: p.value.head,
  fontSize: `${FONT_SIZE.lg}px`,
  fontFamily: 'Calibre-Medium',
  textAlign: 'left',
}));

function openMenu(): void {
  if (props.disabled) return;
  open.value = true;
}

function pick(opt: SelectOption): void {
  emit('update:modelValue', opt.value);
  open.value = false;
}

function clear(): void {
  emit('update:modelValue', '');
}
</script>

<template>
  <div :style="{ position: 'relative', width: block ? '100%' : 'auto', display: 'inline-block' }">
    <button
      type="button"
      :aria-label="name"
      :aria-expanded="open"
      :disabled="disabled"
      :style="triggerStyle"
      @click="openMenu"
    >
      <span :style="labelStyle">{{ current ? current.label : placeholder }}</span>
      <span
        v-if="clearable && current"
        role="button"
        aria-label="Clear"
        :style="{ display: 'inline-flex', cursor: 'pointer' }"
        @click.stop="clear"
      >
        <Icon name="x" :size="16" :color="colors.placeholder" />
      </span>
      <Icon name="selector" :size="16" :color="colors.placeholder" />
    </button>

    <template v-if="open">
      <div
        :style="{ position: 'fixed', inset: '0', zIndex: '40' }"
        @click="open = false"
      />
      <div :style="panelStyle">
        <button
          v-for="opt in options"
          :key="opt.value"
          type="button"
          :style="rowStyle(opt)"
          @click="pick(opt)"
        >
          <span :style="rowLabelStyle">{{ opt.label }}</span>
          <Icon v-if="opt.value === modelValue" name="check" :size="18" :color="p.head" />
        </button>
        <div v-if="options.length === 0" :style="{ padding: '16px' }">
          <span :style="{ color: colors.placeholder, fontFamily: 'Calibre-Medium' }">No options</span>
        </div>
      </div>
    </template>
  </div>
</template>

// packages/kit/src/react-native/select.tsx

import { useState } from 'react';
import {
  Modal,
  Pressable,
  ScrollView,
  Text as RNText,
  View,
  type ViewStyle,
} from 'react-native';
import {
  controlBoxStyle,
  controlColors,
  type ControlSize,
  type ControlVariant,
} from '../control.styles';
import { BLOCK_RADIUS_DEFAULT, FONT_SIZE, schemePalette } from '../tokens';
import { Icon } from './icon';

export interface SelectOption {
  label: string;
  value: string;
}

export interface SelectProps {
  name?: string;
  options?: SelectOption[];
  defaultValue?: string;
  value?: string;
  placeholder?: string;
  variant?: ControlVariant;
  size?: ControlSize;
  pill?: boolean;
  block?: boolean;
  clearable?: boolean;
  disabled?: boolean;
  radius?: number;
  onChange?: (value: string) => void;
  dark?: boolean;
  style?: ViewStyle | ViewStyle[];
}

function styleList(style: ViewStyle | ViewStyle[] | undefined): ViewStyle[] {
  if (!style) return [];
  return Array.isArray(style) ? style : [style];
}

interface SelectTriggerProps {
  name?: string;
  disabled?: boolean;
  block?: boolean;
  clearable?: boolean;
  open: boolean;
  current?: SelectOption;
  placeholder: string;
  box: ViewStyle;
  head: string;
  placeholderColor: string;
  style?: ViewStyle | ViewStyle[];
  onOpen: () => void;
  onClear: () => void;
}

function SelectTrigger(props: SelectTriggerProps): React.ReactElement {
  const { name, disabled, block, clearable, open, current, placeholder, box, head, placeholderColor, style, onOpen, onClear } = props;
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityLabel={name}
      accessibilityState={{ disabled, expanded: open }}
      disabled={disabled}
      onPress={onOpen}
      style={[
        box,
        { flexDirection: 'row', alignItems: 'center', gap: 8, alignSelf: block ? 'stretch' : 'flex-start', opacity: disabled ? 0.5 : 1 },
        ...styleList(style),
      ]}
    >
      <RNText
        numberOfLines={1}
        style={{ flex: 1, color: current ? head : placeholderColor, fontSize: FONT_SIZE.md, fontFamily: 'Calibre-Medium' }}
      >
        {current ? current.label : placeholder}
      </RNText>
      {clearable && current ? (
        <Pressable accessibilityRole="button" accessibilityLabel="Clear" onPress={onClear} hitSlop={8}>
          <Icon name="x" size={16} color={placeholderColor} />
        </Pressable>
      ) : null}
      <Icon name="selector" size={16} color={placeholderColor} />
    </Pressable>
  );
}

function SelectRow(props: {
  opt: SelectOption;
  selected: string | undefined;
  head: string;
  rowBorder: string;
  onPick: (v: string) => void;
}): React.ReactElement {
  const { opt, selected, head, rowBorder, onPick } = props;
  const isSel = opt.value === selected;
  return (
    <Pressable
      accessibilityRole="menuitem"
      accessibilityState={{ selected: isSel }}
      onPress={() => { onPick(opt.value); }}
      style={{
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingHorizontal: 16,
        paddingVertical: 13,
        borderBottomWidth: 1,
        borderBottomColor: rowBorder,
      }}
    >
      <RNText style={{ flex: 1, color: head, fontSize: FONT_SIZE.lg, fontFamily: 'Calibre-Medium' }}>
        {opt.label}
      </RNText>
      {isSel ? <Icon name="check" size={18} color={head} /> : null}
    </Pressable>
  );
}

function SelectSheet(props: {
  open: boolean;
  options: SelectOption[];
  selected: string | undefined;
  sheetBg: string;
  head: string;
  rowBorder: string;
  placeholderColor: string;
  onPick: (v: string) => void;
  onClose: () => void;
}): React.ReactElement {
  const { open, options, selected, sheetBg, head, rowBorder, placeholderColor, onPick, onClose } = props;
  return (
    <Modal visible={open} transparent animationType="fade" onRequestClose={onClose}>
      <Pressable
        style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', padding: 24 }}
        onPress={onClose}
      >
        <Pressable
          style={{ backgroundColor: sheetBg, borderRadius: 14, overflow: 'hidden', maxHeight: '70%' }}
          onPress={() => undefined}
        >
          <ScrollView>
            {options.map((opt) => (
              <SelectRow key={opt.value} opt={opt} selected={selected} head={head} rowBorder={rowBorder} onPick={onPick} />
            ))}
            {options.length === 0 ? (
              <View style={{ padding: 16 }}>
                <RNText style={{ color: placeholderColor, fontFamily: 'Calibre-Medium' }}>No options</RNText>
              </View>
            ) : null}
          </ScrollView>
        </Pressable>
      </Pressable>
    </Modal>
  );
}

export function Select(props: SelectProps): React.ReactElement {
  const {
    name,
    options = [],
    defaultValue,
    value: controlled,
    placeholder = 'Select...',
    variant = 'soft',
    size = 'md',
    pill,
    block,
    clearable,
    disabled,
    radius,
    onChange,
    dark = false,
    style,
  } = props;

  const [internal, setInternal] = useState<string | undefined>(defaultValue);
  const [open, setOpen] = useState(false);
  const selected = controlled ?? internal;

  const colors = controlColors(variant, dark);
  const corner = radius ?? (pill ? 999 : BLOCK_RADIUS_DEFAULT);
  const box = controlBoxStyle(size, variant, colors, corner, false);
  const p = schemePalette(dark);
  const head = p.head;
  const sheetBg = dark ? '#1b1c1e' : '#ffffff';
  const rowBorder = p.border;

  const current = options.find((o) => o.value === selected);

  function pick(v: string): void {
    if (controlled === undefined) setInternal(v);
    onChange?.(v);
    setOpen(false);
  }

  function clear(): void {
    if (controlled === undefined) setInternal(undefined);
    onChange?.('');
  }

  return (
    <>
      <SelectTrigger
        name={name}
        disabled={disabled}
        block={block}
        clearable={clearable}
        open={open}
        current={current}
        placeholder={placeholder}
        box={box}
        head={head}
        placeholderColor={colors.placeholder}
        style={style}
        onOpen={() => { setOpen(true); }}
        onClear={clear}
      />

      <SelectSheet
        open={open}
        options={options}
        selected={selected}
        sheetBg={sheetBg}
        head={head}
        rowBorder={rowBorder}
        placeholderColor={colors.placeholder}
        onPick={pick}
        onClose={() => { setOpen(false); }}
      />
    </>
  );
}
