// packages/kit/src/vue/Tabs.vue
<script setup lang="ts">
import { computed } from 'vue';
import Icon from './Icon.vue';
import { resolveIconName } from './kit-node-props';
import { useKitScheme } from './theme-context';
import type { TabsOption } from '../kit';

const props = withDefaults(
  defineProps<{
    value: string;
    options: TabsOption[];
    variant?: 'segmented' | 'underline';
    dark?: boolean;
  }>(),
  { variant: 'segmented' },
);

const emit = defineEmits<{ 'update:value': [value: string] }>();

const scheme = useKitScheme();
const isDark = computed(() => props.dark ?? scheme === 'dark');
const underline = computed(() => props.variant === 'underline');

const palette = computed(() => ({
  bg: isDark.value ? '#1c1c1e' : '#f0f0f2',
  active: isDark.value ? '#000000' : '#ffffff',
  text: isDark.value ? '#9a9ca0' : '#6b6d72',
  activeText: isDark.value ? '#ffffff' : '#000000',
}));

const containerStyle = computed<Record<string, string>>(() => ({
  display: 'inline-flex',
  flexDirection: 'row',
  gap: underline.value ? '16px' : '4px',
  padding: underline.value ? '0' : '3px',
  borderRadius: '11px',
  backgroundColor: underline.value ? 'transparent' : palette.value.bg,
}));

function tabStyle(selected: boolean): Record<string, string> {
  const p = palette.value;
  if (underline.value) {
    return {
      display: 'inline-flex',
      flexDirection: 'row',
      alignItems: 'center',
      gap: '6px',
      padding: '8px 2px',
      border: '0',
      background: 'none',
      borderBottom: `2px solid ${selected ? p.activeText : 'transparent'}`,
      color: selected ? p.activeText : p.text,
      fontFamily: 'Calibre-Semibold',
      fontSize: '14px',
      cursor: 'pointer',
    };
  }
  return {
    flex: '1',
    display: 'inline-flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    padding: '7px 12px',
    borderRadius: '8px',
    border: '0',
    backgroundColor: selected ? p.active : 'transparent',
    color: selected ? p.activeText : p.text,
    fontFamily: 'Calibre-Semibold',
    fontSize: '14px',
    cursor: 'pointer',
  };
}
</script>

<template>
  <div role="tablist" :style="containerStyle">
    <button
      v-for="opt in options"
      :key="opt.value"
      type="button"
      role="tab"
      :aria-selected="opt.value === value"
      :style="tabStyle(opt.value === value)"
      @click="emit('update:value', opt.value)"
    >
      <Icon
        v-if="opt.icon"
        :name="resolveIconName(opt.icon)"
        :size="16"
        :color="opt.value === value ? palette.activeText : palette.text"
      />
      {{ opt.label }}
    </button>
  </div>
</template>

// packages/kit/src/react-native/tabs.tsx

import { Pressable, Text as RNText, View, type ViewStyle } from 'react-native';
import { Icon } from './icon';
import { FONT_SIZE } from '../tokens';
import type { HeroIconName } from '@stage-labs/kit/icons';

export interface TabsOptionView {
  value: string;
  label: string;
  icon?: HeroIconName;
}

export interface TabsProps {
  value: string;
  options: TabsOptionView[];
  variant?: 'segmented' | 'underline';
  onChange?: (value: string) => void;
  dark?: boolean;
}

function palette(dark: boolean): {
  bg: string;
  active: string;
  text: string;
  activeText: string;
} {
  return {
    bg: dark ? '#1c1c1e' : '#f0f0f2',
    active: dark ? '#000000' : '#ffffff',
    text: dark ? '#9a9ca0' : '#6b6d72',
    activeText: dark ? '#ffffff' : '#000000',
  };
}

function segmentStyle(selected: boolean, p: ReturnType<typeof palette>): ViewStyle {
  return {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: selected ? p.active : 'transparent',
  };
}

export function Tabs(props: TabsProps): React.ReactElement {
  const { value, options, variant = 'segmented', onChange, dark = false } = props;
  const p = palette(dark);
  const underline = variant === 'underline';
  return (
    <View
      style={{
        flexDirection: 'row',
        gap: underline ? 16 : 4,
        padding: underline ? 0 : 3,
        borderRadius: 11,
        backgroundColor: underline ? 'transparent' : p.bg,
      }}
    >
      {options.map((opt) => {
        const selected = opt.value === value;
        return (
          <Pressable
            key={opt.value}
            accessibilityRole="tab"
            accessibilityState={{ selected }}
            onPress={() => onChange?.(opt.value)}
            style={
              underline
                ? {
                    flexDirection: 'row',
                    alignItems: 'center',
                    gap: 6,
                    paddingVertical: 8,
                    borderBottomWidth: 2,
                    borderBottomColor: selected ? p.activeText : 'transparent',
                  }
                : segmentStyle(selected, p)
            }
          >
            {opt.icon ? (
              <Icon
                name={opt.icon}
                size={16}
                color={selected ? p.activeText : p.text}
              />
            ) : null}
            <RNText
              style={{
                color: selected ? p.activeText : p.text,
                fontSize: underline ? FONT_SIZE['3xl'] : FONT_SIZE.sm,
                fontFamily: 'Calibre-Semibold',
              }}
            >
              {opt.label}
            </RNText>
          </Pressable>
        );
      })}
    </View>
  );
}
