// packages/kit/src/vue/TextField.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { controlColors, textFieldSpec } from '../control.styles';
import { BLOCK_RADIUS_DEFAULT } from '../tokens';
import { useKitScheme } from './theme-context';

const props = withDefaults(
  defineProps<{
    name?: string;
    value: string;
    placeholder?: string;
    multiline?: boolean;
    autoFocus?: boolean;
    autoGrow?: boolean;
    disabled?: boolean;
    selection?: { start: number; end: number };
    focusNonce?: number;
    variant?: 'outline' | 'plain';
    background?: string;
    borderColor?: string;
    radius?: number | string;
    paddingX?: number | string;
    paddingY?: number | string;
    fontSize?: number;
    fontFamily?: string;
    color?: string;
    placeholderColor?: string;
    maxLength?: number;
    maxHeight?: number | string;
    enterKeyHint?: 'done' | 'go' | 'next' | 'search' | 'send';
    autoCapitalize?: 'none' | 'sentences' | 'words' | 'characters';
    autoCorrect?: boolean;
    dark?: boolean;
  }>(),
  {},
);

const emit = defineEmits<{
  'update:value': [value: string];
  selectionChange: [range: { start: number; end: number }];
  submit: [];
}>();

const scheme = useKitScheme();
const isDark = computed(() => props.dark ?? scheme === 'dark');
const focused = ref(false);
const inputEl = ref<HTMLInputElement | HTMLTextAreaElement | null>(null);

watch(
  () => props.focusNonce,
  (next, prev) => {
    if (next === undefined || next === prev) return;
    inputEl.value?.focus();
  },
);

function px(v: number | string | undefined): string | undefined {
  if (v === undefined) return undefined;
  return typeof v === 'number' ? `${v}px` : v;
}

const spec = computed(() => {
  const baseColors = controlColors(
    props.variant === 'plain' ? 'soft' : 'outline',
    isDark.value,
  );
  return textFieldSpec({
    variant: props.variant,
    focused: focused.value,
    defaultRadius: BLOCK_RADIUS_DEFAULT,
    baseColors,
    background: props.background,
    borderColor: props.borderColor,
    radius: props.radius,
    paddingX: props.paddingX,
    paddingY: props.paddingY,
    fontSize: props.fontSize,
    fontFamily: props.fontFamily,
    color: props.color,
  });
});

const style = computed<Record<string, string>>(() => {
  const s = spec.value;
  const padX = px(s.paddingX) ?? '0';
  const padY = px(s.paddingY) ?? '0';
  const css: Record<string, string> = {
    minHeight: props.multiline
      ? props.autoGrow
        ? '44px'
        : '88px'
      : `${s.minHeight}px`,
    paddingLeft: padX,
    paddingRight: padX,
    paddingTop: padY,
    paddingBottom: padY,
    backgroundColor: s.background,
    borderRadius: px(s.radius) ?? '0',
    borderWidth: `${s.borderWidth}px`,
    borderColor: s.borderColor,
    color: s.color,
    fontSize: `${s.fontSize}px`,
    fontFamily: s.fontFamily,
    borderStyle: 'solid',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  };
  if (props.multiline) {
    css.textAlign = 'left';
    css.resize = 'none';
  }
  const maxH = px(props.maxHeight);
  if (maxH !== undefined) css.maxHeight = maxH;
  if (props.disabled) css.opacity = '0.5';
  return css;
});

const placeholderColor = computed(() => {
  if (props.placeholderColor !== undefined) return props.placeholderColor;
  return controlColors('outline', isDark.value).placeholder;
});

const autocorrectAttr = computed<'on' | 'off' | undefined>(() => {
  if (props.autoCorrect === undefined) return undefined;
  return props.autoCorrect ? 'on' : 'off';
});

const spellcheckAttr = computed<boolean | undefined>(() => {
  if (props.autoCorrect === undefined) return undefined;
  return props.autoCorrect;
});

function onInput(event: Event): void {
  const target = event.target as HTMLInputElement | HTMLTextAreaElement;
  emit('update:value', target.value);
  emitSelection(target);
}

function emitSelection(target: HTMLInputElement | HTMLTextAreaElement): void {
  const start = target.selectionStart;
  const end = target.selectionEnd;
  if (start === null || end === null) return;
  emit('selectionChange', { start, end });
}

function onSelect(event: Event): void {
  emitSelection(event.target as HTMLInputElement | HTMLTextAreaElement);
}

function onKeyup(event: KeyboardEvent): void {
  onSelect(event);
  if (!props.multiline && event.key === 'Enter') emit('submit');
}
</script>

<template>
  <textarea
    v-if="multiline"
    ref="inputEl"
    :name="name"
    :value="value"
    :placeholder="placeholder"
    :disabled="disabled"
    :autofocus="autoFocus"
    :maxlength="maxLength"
    :enterkeyhint="enterKeyHint"
    :autocapitalize="autoCapitalize"
    :autocorrect="autocorrectAttr"
    :spellcheck="spellcheckAttr"
    :style="{ ...style, '--kit-placeholder': placeholderColor }"
    @input="onInput"
    @select="onSelect"
    @keyup="onKeyup"
    @click="onSelect"
    @focus="focused = true"
    @blur="focused = false"
  />
  <input
    v-else
    ref="inputEl"
    :name="name"
    :value="value"
    :placeholder="placeholder"
    :disabled="disabled"
    :autofocus="autoFocus"
    :maxlength="maxLength"
    :enterkeyhint="enterKeyHint"
    :autocapitalize="autoCapitalize"
    :autocorrect="autocorrectAttr"
    :spellcheck="spellcheckAttr"
    :style="{ ...style, '--kit-placeholder': placeholderColor }"
    @input="onInput"
    @select="onSelect"
    @keyup="onKeyup"
    @click="onSelect"
    @focus="focused = true"
    @blur="focused = false"
  />
</template>

<style scoped>
input::placeholder,
textarea::placeholder {
  color: var(--kit-placeholder);
}
</style>

// packages/kit/src/react-native/text-field.tsx

import { useEffect, useRef, useState } from 'react';
import {
  TextInput,
  type DimensionValue,
  type ReturnKeyTypeOptions,
  type TextStyle,
} from 'react-native';
import {
  controlColors,
  textFieldStyle,
  type TextFieldVariant,
} from '../control.styles';
import { BLOCK_RADIUS_DEFAULT } from '../tokens';

export interface TextFieldProps {
  name?: string;
  value: string;
  placeholder?: string;
  multiline?: boolean;
  autoFocus?: boolean;
  autoGrow?: boolean;
  disabled?: boolean;
  onChangeText?: (text: string) => void;
  selection?: { start: number; end: number };
  onSelectionChange?: (range: { start: number; end: number }) => void;
  onSubmit?: () => void;
  focusNonce?: number;
  variant?: TextFieldVariant;
  background?: string;
  borderColor?: string;
  radius?: number | string;
  paddingX?: number | string;
  paddingY?: number | string;
  fontSize?: number;
  fontFamily?: string;
  color?: string;
  placeholderColor?: string;
  maxLength?: number;
  maxHeight?: number | string;
  returnKeyType?: ReturnKeyTypeOptions;
  autoCapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autoCorrect?: boolean;
  dark?: boolean;
}

export function TextField(props: TextFieldProps): React.ReactElement {
  const {
    value,
    placeholder,
    multiline,
    autoFocus,
    autoGrow,
    disabled,
    onChangeText,
    selection,
    onSelectionChange,
    onSubmit,
    focusNonce,
    variant,
    background,
    borderColor,
    radius,
    paddingX,
    paddingY,
    fontSize,
    fontFamily,
    color,
    placeholderColor,
    maxLength,
    maxHeight,
    returnKeyType,
    autoCapitalize,
    autoCorrect,
    dark = false,
  } = props;
  const [focused, setFocused] = useState(false);
  const ref = useRef<TextInput>(null);

  useEffect(() => {
    if (focusNonce === undefined) return;
    ref.current?.focus();
  }, [focusNonce]);

  const baseColors = controlColors(
    variant === 'plain' ? 'soft' : 'outline',
    dark,
  );
  const styled = textFieldStyle({
    variant,
    focused,
    defaultRadius: BLOCK_RADIUS_DEFAULT,
    baseColors,
    background,
    borderColor,
    radius,
    paddingX,
    paddingY,
    fontSize,
    fontFamily,
    color,
  });
  const maxH = maxHeight as DimensionValue | undefined;
  const grow: TextStyle = multiline
    ? {
        minHeight: autoGrow ? 44 : 88,
        maxHeight: maxH,
        height: undefined,
        textAlignVertical: 'top',
      }
    : { maxHeight: maxH };

  return (
    <TextInput
      ref={ref}
      value={value}
      placeholder={placeholder}
      placeholderTextColor={placeholderColor ?? styled.placeholder}
      editable={!disabled}
      autoFocus={autoFocus}
      multiline={multiline}
      maxLength={maxLength}
      returnKeyType={returnKeyType}
      autoCapitalize={autoCapitalize}
      autoCorrect={autoCorrect}
      onChangeText={onChangeText}
      onSubmitEditing={onSubmit}
      selection={selection}
      onSelectionChange={
        onSelectionChange === undefined
          ? undefined
          : (event) => {
              onSelectionChange(event.nativeEvent.selection);
            }
      }
      onFocus={() => {
        setFocused(true);
      }}
      onBlur={() => {
        setFocused(false);
      }}
      style={[styled.box, styled.text, grow, disabled ? { opacity: 0.5 } : null]}
    />
  );
}
