// apps/stage/components/CommonChannels.tsx

import { Pressable } from '@stage-labs/kit/react-native/pressable';

import { Text } from '@stage-labs/kit/react-native/text';
import { Box, Row, PAGE_GUTTER } from './layout';
import { Spinner } from '@stage-labs/kit/react-native/spinner';
import { useRouter } from 'expo-router';
import { ChannelRow } from './ChannelRow';
import { useCommonChannels } from '../lib/useCommonChannels';
import { getDraft } from '../lib/drafts';
import { isPinned } from '../lib/pins';
import type { Palette } from '../lib/theme';
import { channelTimestamp } from '../lib/format';
import { peerLabel } from './conversation/convTitle';

export function CommonChannels({ peerAddress, enabled, c }: {
  peerAddress: string | null;
  enabled: boolean;
  c: Palette;
}): React.ReactElement | null {
  const router = useRouter();
  const { channels, loading } = useCommonChannels(peerAddress, enabled);

  if (channels.length === 0 && !loading) return null;

  return (
    <Box margin={{ top: 20 }}>
      <Row margin={{ x: PAGE_GUTTER, bottom: 6 }} justify="start" align="center" gap={24} 
        style={{ borderBottomWidth: 1, borderBottomColor: c.border }}>
        <Pressable style={{ paddingVertical: 10, marginBottom: -1, borderBottomWidth: 2, borderBottomColor: c.link }}>
          <Text weight="semibold" size="lg" color={c.link}>
            Channels
          </Text>
        </Pressable>
        {loading ? <Spinner size={20} color={c.text} /> : null}
      </Row>

      {channels.map(ch => {
        const hasMsg = ch.lastPreview.length> 0;
        const preview = hasMsg
          ? `${ch.lastSenderAddress ? `${peerLabel(ch.lastSenderAddress)}: ` : ''}${ch.lastPreview}`
          : null;
        const showAddr = ch.avatarUri || !ch.avatarAddress ? null : ch.avatarAddress;
        return (
          <ChannelRow
            key={ch.convId}
            title={ch.title}
            placeholderTitle={ch.placeholderTitle}
            avatarUri={ch.avatarUri}
            avatarAddress={showAddr}
            square
            lastPreview={preview}
            subtitle={`${ch.memberCount} member${ch.memberCount === 1 ? '' : 's'}`}
            timestamp={channelTimestamp(ch.lastTs)}
            unreadCount={ch.unreadCount}
            markedUnread={ch.markedUnread}
            pinned={isPinned(ch.convId)}
            draftText={getDraft(ch.convId)}
            onPress={() => { router.push({ pathname: '/channel/[convId]', params: { convId: ch.convId } }); }}
          />
        );
      })}
    </Box>
  );
}

// apps/ui/src/components/CommonChannels.vue
<script setup lang="ts">

import { computed, toRef } from 'vue';
import { useRouter } from 'vue-router';
import { useKitPalette } from '@stage-labs/kit/vue/theme-context';
import { useCommonChannels } from '../lib/useCommonChannels';

const props = defineProps<{ peerAddress: string | null; enabled: boolean }>();

const router = useRouter();
const palette = useKitPalette();

const { channels, loading } = useCommonChannels(
  toRef(props, 'peerAddress'),
  toRef(props, 'enabled'),
);

const show = computed(() => loading.value || channels.value.length > 0);

function open(convId: string): void {
  void router.push(`/xmtp/${convId}`);
}
</script>

<template>
  <!-- Mutual group memberships with this peer, mirroring mobile CommonChannels:
       a "Channels" tab header (with a spinner while resolving) over reused
       ChannelRow list items. Hidden entirely when there are no common channels. -->
  <Col v-if="show" class="mt-5">
    <Row
      align="center"
      justify="start"
      :gap="24"
      class="mx-4 mb-1.5 border-b"
      :style="{ borderColor: palette.border }"
    >
      <Col
        class="py-2.5 -mb-px border-b-2"
        :style="{ borderColor: palette.link }"
      >
        <Text size="3xl" weight="semibold" color="link">Channels</Text>
      </Col>
      <Spinner v-if="loading" :size="20" />
    </Row>

    <ChannelRow
      v-for="ch in channels"
      :key="ch.convId"
      :title="ch.title"
      :avatar-uri="ch.avatarUri"
      :avatar-address="ch.avatarUri ? null : ch.avatarAddress"
      :last-ts="ch.lastTs"
      :last-preview="ch.lastPreview"
      :subtitle="`${ch.memberCount} member${ch.memberCount === 1 ? '' : 's'}`"
      :unread-count="ch.unreadCount"
      :marked-unread="ch.markedUnread"
      @open="open(ch.convId)"
    />
  </Col>
</template>
