// apps/app/components/tabs/Proposals.banner.tsx

import { ViewHost } from '@stage-labs/kit/react-native/view-host';
import type { PayloadHandlers } from '@stage-labs/kit/kit';
import { banner, listRoot, navigateAction, BANNER_PRESS } from '@stage-labs/views';
import { capabilities } from '../../lib/capabilities';
import { Box } from '../layout';
import { usePalette } from '../../lib/theme';
import { useProposalCount } from './Proposals.hook';

export function ProposalsBanner(): React.ReactElement | null {
  const pal = usePalette();
  const count = useProposalCount();

  if (count <= 0) return null;

  const node = listRoot(banner({
    icon: 'statusOnline',
    label: count === 1 ? '1 pending request' : `${count} pending requests`,
  }));
  const actions: PayloadHandlers = {
    ...navigateAction(BANNER_PRESS, capabilities, () => '/proposals'),
  };

  return (
    <Box
      surface="surface"
      padding={{ x: 16, y: 12 }}
      style={{ borderBottomWidth: 1, borderBottomColor: pal.border }}
    >
      <ViewHost node={node} actions={actions} />
    </Box>
  );
}

// apps/ui/src/components/ProposalsBanner.vue
<script setup lang="ts">

import { computed } from 'vue';
import ViewHost from '@stage-labs/kit/vue/view-host';
import { listRoot, banner, navigateAction, BANNER_PRESS } from '@stage-labs/views';
import { capabilities } from '@/lib/capabilities';
import { useProposalCount } from '../lib/useProposals';

const { count } = useProposalCount();

const node = computed(() =>
  listRoot(
    banner({
      icon: 'statusOnline',
      label: count.value === 1 ? '1 pending request' : `${count.value} pending requests`,
    }),
  ),
);

const actions = {
  ...navigateAction(BANNER_PRESS, capabilities, () => '/proposals'),
};
</script>

<template>
  <Box
    v-if="count > 0"
    class="w-full shrink-0 border-b border-metro-border-light dark:border-metro-border-dark"
  >
    <ViewHost :node="node" :actions="actions" />
  </Box>
</template>
