// apps/stage/components/Topnav.tsx

import { TopnavIdentity } from './TopnavIdentity';
import { Row, WebFullBleed } from './layout';
import { usePalette } from '../lib/theme';

export const TOPNAV_HEIGHT = 52;

export function Topnav({ left, right }: {
  left?: React.ReactNode;
  right?: React.ReactNode;
}): React.ReactElement {
  const { border } = usePalette();

  const content = (
    <>
      <Row align="center" gap={8}>
        {left ?? <TopnavIdentity/>}
      </Row>
      {right ? (
        <Row align="center" gap={18}>
          {right}
        </Row>
      ) : null}
    </>
  );

  return (
    <WebFullBleed>
      <Row
        height={TOPNAV_HEIGHT}
        padding={{ x: 16 }}
        align="center"
        justify="between"
        surface="toolbar"
        style={{ borderBottomWidth: 1, borderBottomColor: border }}
      >
        {content}
      </Row>
    </WebFullBleed>
  );
}

// apps/ui/src/components/Topnav.vue
<script setup lang="ts">
import { useTopnavOverride } from '@/lib/topnavSlots';
import TopnavIdentity from './TopnavIdentity.vue';

const override = useTopnavOverride();
</script>

<template>
  <Col
    class="shrink-0 bg-metro-bg-light dark:bg-metro-bg-dark
      border-b border-metro-border-light dark:border-metro-border-dark"
  >
    <Col v-show="override" id="topnav-override" />
    <Row
      v-show="!override"
      align="center"
      justify="between"
      class="h-[52px] box-border px-4"
    >
      <Row align="center" :gap="8">
        <TopnavIdentity />
      </Row>
      <Row id="topnav-right" align="center" :gap="18" />
    </Row>
  </Col>
</template>
