// apps/ui/src/components/EditProfileModal.vue
<script setup lang="ts">
/** Edit-profile sheet: same fields as the mobile counterpart. Picks an avatar
 *  file (JPEG/PNG → pineapple → ipfs://), signs EIP-712 with the local viem
 *  account, POSTs to the Snapshot sequencer. */

import { type SnapshotProfile, updateProfile, uploadAvatar } from '../lib/profile';
import { PROFILE_FIELD_LIMITS } from '@stage-labs/metro-client/profile/snapshot';
import { stampBoxAvatarUrl } from '../lib/xmtp';

const props = defineProps<{ open: boolean; address: string; initial: SnapshotProfile }>();
const emit = defineEmits<{ (e: 'close'): void; (e: 'saved', next: SnapshotProfile): void }>();

interface Field { key: keyof SnapshotProfile; label: string; placeholder: string; multiline?: boolean }
const FIELDS: Field[] = [
  { key: 'name', label: 'Name', placeholder: 'Display name' },
  { key: 'about', label: 'About', placeholder: 'Tell your story', multiline: true },
  { key: 'github', label: 'GitHub', placeholder: 'GitHub handle' },
  { key: 'twitter', label: 'X (Twitter)', placeholder: 'X handle' },
  { key: 'lens', label: 'Lens', placeholder: 'Lens handle' },
  { key: 'farcaster', label: 'Farcaster', placeholder: 'Farcaster handle' },
];

const form = ref<SnapshotProfile>({ ...props.initial });
const saving = ref(false);
const uploading = ref(false);
const error = ref<string | null>(null);
const fileInput = ref<HTMLInputElement | null>(null);

watch(() => [props.open, props.initial] as const, ([open]) => {
  if (open) { form.value = { ...props.initial }; error.value = null; }
});

function update(k: keyof SnapshotProfile, v: string): void {
  const max = (PROFILE_FIELD_LIMITS as Record<string, number>)[k];
  (form.value as Record<string, string>)[k] = max ? v.slice(0, max) : v;
}

async function onPickFile(e: Event): Promise<void> {
  const file = (e.target as HTMLInputElement).files?.[0];
  if (!file) return;
  uploading.value = true; error.value = null;
  try {
    const url = await uploadAvatar(file);
    form.value = { ...form.value, avatar: url };
  } catch (err) { error.value = (err as Error).message; }
  finally { uploading.value = false; if (fileInput.value) fileInput.value.value = ''; }
}

async function save(): Promise<void> {
  saving.value = true; error.value = null;
  try {
    await updateProfile(form.value);
    emit('saved', { ...form.value });
    emit('close');
  } catch (err) { error.value = (err as Error).message; }
  finally { saving.value = false; }
}
</script>

<template>
  <div v-if="open"
    class="fixed inset-0 z-50 flex items-end sm:items-center justify-center
      bg-black/60 backdrop-blur-sm"
    @click.self="emit('close')">
    <div class="w-full sm:max-w-md sm:rounded-2xl rounded-t-2xl
      bg-metro-bg-light dark:bg-metro-bg-dark
      border-t sm:border border-metro-border-light dark:border-metro-border-dark
      max-h-[90vh] flex flex-col">
      <div class="flex items-center justify-between px-4 py-3 border-b border-metro-border-light dark:border-metro-border-dark">
        <button type="button" class="text-metro-sub-light dark:text-metro-sub-dark text-sm" :disabled="saving" @click="emit('close')">Cancel</button>
        <div class="font-head text-metro-head-light dark:text-metro-head-dark text-base">Edit profile</div>
        <button type="button" class="font-head text-sm"
          :class="saving || uploading ? 'text-metro-sub-light dark:text-metro-sub-dark' : 'text-metro-head-light dark:text-metro-head-dark'"
          :disabled="saving || uploading" @click="save">
          {{ saving ? 'Saving…' : 'Save' }}
        </button>
      </div>
      <div class="overflow-y-auto p-4">
        <div class="flex flex-col items-center mb-5">
          <button type="button" :disabled="uploading"
            class="relative rounded-full overflow-hidden bg-metro-surface-light dark:bg-metro-surface-dark disabled:opacity-50"
            @click="fileInput?.click()">
            <img :src="stampBoxAvatarUrl(address, 192)" alt="" class="w-24 h-24 rounded-full object-cover" />
            <div v-if="uploading" class="absolute inset-0 flex items-center justify-center bg-black/40 text-white text-xs">…</div>
          </button>
          <div class="text-xs text-metro-sub-light dark:text-metro-sub-dark mt-2">Tap to change avatar</div>
          <input ref="fileInput" type="file" accept="image/jpeg,image/jpg,image/png" class="hidden" @change="onPickFile" />
        </div>

        <div v-if="error" class="mb-3 p-2 rounded-lg bg-metro-err/20 text-metro-err text-xs">{{ error }}</div>

        <div v-for="f in FIELDS" :key="f.key" class="mb-3">
          <label class="block text-[11px] text-metro-sub-light dark:text-metro-sub-dark mb-1">{{ f.label.toUpperCase() }}</label>
          <textarea v-if="f.multiline" :value="(form[f.key] ?? '') as string"
            :placeholder="f.placeholder" rows="3"
            class="w-full bg-metro-surface-light dark:bg-metro-surface-dark border border-metro-border-light dark:border-metro-border-dark rounded-xl p-3 text-sm text-metro-fg-light dark:text-metro-fg-dark"
            @input="update(f.key, ($event.target as HTMLTextAreaElement).value)" />
          <input v-else type="text" :value="(form[f.key] ?? '') as string"
            :placeholder="f.placeholder"
            class="w-full bg-metro-surface-light dark:bg-metro-surface-dark border border-metro-border-light dark:border-metro-border-dark rounded-xl p-3 text-sm text-metro-fg-light dark:text-metro-fg-dark"
            @input="update(f.key, ($event.target as HTMLInputElement).value)" />
        </div>
      </div>
    </div>
  </div>
</template>

// apps/app/components/EditProfileModal.tsx
/** Edit-profile sheet: avatar picker + name / about / social handle inputs.
 *  Signs an EIP-712 envelope and POSTs it to the Snapshot sequencer via
 *  `lib/profile.ts`. Closes on success and emits the new profile so the parent
 *  refreshes immediately. */

import { useEffect, useState } from 'react';
import { fontSize } from '@metro-labs/kit/tokens';
import { Alert, KeyboardAvoidingView, Modal, Platform } from 'react-native';
import { Pressable } from '@metro-labs/kit/pressable';
import { Scroll as ScrollView } from '@metro-labs/kit/scroll';
import { Input } from '@metro-labs/kit/input';
import { Textarea } from '@metro-labs/kit/textarea';
import { Avatar } from './Avatar';
import { Text } from '@metro-labs/kit/text';
import { Box, Row } from './layout';
import { Button } from '@metro-labs/kit/button';
import { Spinner } from './Spinner';
import { Icon } from '@metro-labs/kit/icon';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import * as ImagePicker from 'expo-image-picker';
import {
  type SnapshotProfile, updateProfile, uploadAvatar,
} from '../lib/profile';
import { PROFILE_FIELD_LIMITS, getCacheHash } from '@stage-labs/client/profile/snapshot';
import { setPeerProfile } from '../lib/peerProfiles';
import { usePalette, useBlockRadius } from '../lib/theme';

const AVATAR_SIZE = 96;

interface Field { key: keyof SnapshotProfile; label: string; placeholder: string; multiline?: boolean }
const FIELDS: Field[] = [
  { key: 'name', label: 'Name', placeholder: 'Display name' },
  { key: 'about', label: 'About', placeholder: 'Tell your story', multiline: true },
  { key: 'github', label: 'GitHub', placeholder: 'GitHub handle' },
  { key: 'twitter', label: 'X (Twitter)', placeholder: 'X handle' },
];

export default function EditProfileModal({
  visible, onClose, onSaved, address, initial, dark,
}: {
  visible: boolean; onClose: () => void;
  onSaved: (next: SnapshotProfile) => void;
  address: string; initial: SnapshotProfile; dark: boolean;
}): React.ReactElement {
  const { text: fg, link: head, bg, border, primary, inputBg } = usePalette();
  const blockRadius = useBlockRadius();
  const sub = fg;
  const rowBg = border;
  const insets = useSafeAreaInsets();

  const [form, setForm] = useState<SnapshotProfile>(initial);
  const [saving, setSaving] = useState(false);
  const [uploading, setUploading] = useState(false);
  /** Re-seed the form whenever the parent reopens us with a fresh `initial`. */
  useEffect(() => { if (visible) setForm(initial); }, [visible, initial]);

  const pickAvatar = async (): Promise<void> => {
    const r = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: 'images', quality: 0.85, allowsMultipleSelection: false,
      /** Built-in square crop/resize step before upload — `allowsEditing` is
       *  part of expo-image-picker, no extra native dep. */
      allowsEditing: true, aspect: [1, 1],
    });
    if (r.canceled || !r.assets?.length) return;
    const a = r.assets[0];
    setUploading(true);
    try {
      const url = await uploadAvatar(a.uri, a.mimeType ?? 'image/jpeg', a.fileName ?? 'avatar');
      setForm(prev => ({ ...prev, avatar: url }));
    } catch (e) { Alert.alert('Upload failed', (e as Error).message); }
    finally { setUploading(false); }
  };

  const save = async (): Promise<void> => {
    setSaving(true);
    try {
      await updateProfile(form);
      /** Push the new name/avatar into the shared peer-profile cache so every
       *  surface that renders the local user (group member rows, message
       *  bubbles, conversation topnav) reflects the change — incl. a fresh
       *  avatar cache-buster — without an app reload. */
      if (address) setPeerProfile(address, { name: form.name, avatar: form.avatar });
      onSaved(form);
      onClose();
    } catch (e) { Alert.alert('Save failed', (e as Error).message); }
    finally { setSaving(false); }
  };

  const update = <K extends keyof SnapshotProfile>(k: K, v: string): void => {
    const max = PROFILE_FIELD_LIMITS[k as keyof typeof PROFILE_FIELD_LIMITS];
    setForm(prev => ({ ...prev, [k]: max ? v.slice(0, max) : v }));
  };

  return (
    <Modal visible={visible} onRequestClose={onClose} animationType="slide" transparent={false}>
      <KeyboardAvoidingView style={{ flex: 1, backgroundColor: bg }}
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
        {/** No title / Cancel chrome — a single close X is the dismiss affordance
         *  (this is a full-screen modal with no backdrop tap). */}
        <Row align="center" justify="end" px={16} pt={insets.top + 12} pb={12}>
          <Pressable onPress={onClose} disabled={saving} hitSlop={10}>
            <Icon name="x" size={24} color={head} />
          </Pressable>
        </Row>
        <ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 48 }} keyboardShouldPersistTaps="handled">
          <Box align="center" mb={20}>
            <Pressable onPress={pickAvatar} disabled={uploading}>
              <Avatar
                address={address}
                size={AVATAR_SIZE}
                cacheBuster={getCacheHash(form.avatar)}
                style={{ backgroundColor: rowBg, opacity: uploading ? 0.5 : 1 }}
              />
              {uploading ? (
                <Box align="center" justify="center" style={{ position: 'absolute', inset: 0 }}>
                  <Spinner size={20} color={fg} />
                </Box>
              ) : null}
            </Pressable>
            <Text size="xs" color={sub} style={{ marginTop: 8 }}>Tap to change avatar</Text>
          </Box>

          {FIELDS.map(f => (
            <Box key={f.key} mb={14}>
              <Text size="3xs" color={sub} style={{ marginBottom: 4 }}>{f.label.toUpperCase()}</Text>
              {f.multiline ? (
                <Textarea
                  value={(form[f.key] ?? '') as string}
                  onChangeText={t => update(f.key, t)}
                  placeholder={f.placeholder}
                  placeholderTextColor={sub}
                  dark={dark}
                  style={{
                    color: fg, backgroundColor: inputBg, borderColor: border, borderWidth: 1,
                    borderRadius: blockRadius, padding: 12, fontSize: fontSize('md'),
                    minHeight: 80, height: undefined, textAlignVertical: 'top',
                  }}
                />
              ) : (
                <Input
                  value={(form[f.key] ?? '') as string}
                  onChangeText={t => update(f.key, t)}
                  placeholder={f.placeholder}
                  placeholderTextColor={sub}
                  dark={dark}
                  style={{
                    color: fg, backgroundColor: inputBg, borderColor: border, borderWidth: 1,
                    borderRadius: blockRadius, padding: 12, fontSize: fontSize('md'),
                    minHeight: 0, textAlignVertical: 'center',
                  }}
                />
              )}
            </Box>
          ))}

          <Button
            variant="primary"
            size="lg"
            fullWidth
            dark={dark}
            disabled={saving || uploading}
            onPress={() => { void save(); }}
            label={saving ? 'Saving…' : 'Save'}
            tintBg={primary}
            tintFg={bg}
            style={{ marginTop: 16 }}
            textStyle={{ fontFamily: 'Calibre-Medium' }}
          />
        </ScrollView>
      </KeyboardAvoidingView>
    </Modal>
  );
}
