// apps/ui/src/components/EventRow.vue
<script setup lang="ts">
import type { HistoryEntry } from '../lib/types';

const props = defineProps<{ entry: HistoryEntry }>();
const router = useRouter();
const MAX_BODY = 140;

const text = computed(() => {
  const b = props.entry.text ?? '(no text)';
  return b.length > MAX_BODY ? b.slice(0, MAX_BODY - 1) + '…' : b;
});
const sender = computed(() => (props.entry.fromName ?? props.entry.from).replace(/^metro:\/\//, ''));
const lineLabel = computed(() => props.entry.lineName ?? props.entry.line.replace(/^metro:\/\//, ''));
const ts = computed(() => {
  try { return new Date(props.entry.ts).toLocaleTimeString([], { hour12: false }); }
  catch { return props.entry.ts.slice(11, 19); }
});

function open(): void {
  void router.push({
    name: 'event', params: { id: props.entry.id },
    query: { data: JSON.stringify(props.entry) },
  });
}
</script>

<template>
  <button
    type="button"
    class="w-full text-left px-3 py-1.5 hover:opacity-80 transition-opacity flex items-start gap-2.5"
    @click="open"
  >
    <div class="pt-1"><StationIcon :station="entry.station" /></div>
    <div class="flex-1 min-w-0 flex flex-col gap-0.5">
      <div class="flex items-baseline gap-1.5">
        <span class="text-[13px] font-semibold text-metro-fg-light dark:text-metro-fg-dark truncate">{{ sender }}</span>
        <span class="text-[11px] text-metro-sub-light dark:text-metro-sub-dark">{{ ts }}</span>
      </div>
      <div class="text-[11px] text-metro-sub-light dark:text-metro-sub-dark truncate">{{ lineLabel }}</div>
      <!-- Messenger-style bubble for the body. -->
      <div class="mt-1 px-3 py-2 rounded-2xl rounded-tl-sm bg-metro-surface-light dark:bg-metro-surface-dark">
        <div class="text-[15px] leading-snug text-metro-fg-light dark:text-metro-fg-dark whitespace-pre-wrap line-clamp-4">{{ text }}</div>
      </div>
    </div>
  </button>
</template>

// apps/app/components/EventRow.tsx
import { Pressable, Text, View, useColorScheme } from 'react-native';
import { StationIcon } from './StationIcon';
import type { HistoryEntry } from '../lib/types';

const MAX_BODY = 140;

function fmtTs(ts: string): string {
  /** ISO timestamp → HH:MM:SS, in local time (Date does the conversion). */
  try { return new Date(ts).toLocaleTimeString([], { hour12: false }); }
  catch { return ts.slice(11, 19); }
}

export function EventRow({ entry, onPress, unread = false }: {
  entry: HistoryEntry; onPress: () => void; unread?: boolean;
}): React.ReactElement {
  const dark = useColorScheme() === 'dark';
  const sub = dark ? '#8a94a6' : '#5a6477';
  const body = entry.text ?? '(no text)';
  const trunc = body.length > MAX_BODY ? body.slice(0, MAX_BODY - 1) + '…' : body;
  const sender = (entry.fromName ?? entry.from).replace(/^metro:\/\//, '');

  const fg = dark ? '#e8ecf2' : '#1a1f29';
  const bubbleBg = dark ? '#16191f' : '#f3f5f9';
  return (
    <Pressable
      onPress={onPress}
      style={({ pressed }) => ({
        paddingHorizontal: 14, paddingVertical: 6,
        opacity: pressed ? 0.7 : 1,
        flexDirection: 'row', alignItems: 'flex-start', gap: 10,
      })}
    >
      <View style={{ paddingTop: 4 }}><StationIcon station={entry.station} /></View>
      <View style={{ flex: 1, gap: 2 }}>
        <View style={{ flexDirection: 'row', alignItems: 'baseline', gap: 6 }}>
          <Text style={{ fontSize: 13, color: fg, fontFamily: 'Calibre-Semibold' }} numberOfLines={1}>{sender}</Text>
          <Text style={{ fontSize: 11, color: sub }}>{fmtTs(entry.ts)}</Text>
        </View>
        <Text style={{ fontSize: 11, color: sub }} numberOfLines={1}>
          {entry.lineName ?? entry.line.replace(/^metro:\/\//, '')}
        </Text>
        {/** Messenger-style bubble for the body. */}
        <View style={{
          backgroundColor: bubbleBg, paddingHorizontal: 12, paddingVertical: 8,
          borderRadius: 16, borderTopLeftRadius: 4, marginTop: 4,
          borderLeftWidth: unread ? 2 : 0, borderLeftColor: unread ? '#ffffff' : 'transparent',
        }}>
          <Text style={{ fontSize: 15, color: fg, lineHeight: 21 }} numberOfLines={4}>
            {trunc}
          </Text>
        </View>
      </View>
    </Pressable>
  );
}
