// apps/ui/src/components/VoiceMessage.vue
<script setup lang="ts">

import { computed, ref, watch } from 'vue';
import ViewHost from '@stage-labs/kit/vue/view-host';
import { basicRoot, voiceMessage, VOICE_PLAY } from '@stage-labs/views';
import {
  VOICE_BAR_COUNT, voiceWaveformBars, voiceBucketRms,
} from '@stage-labs/client/xmtp/voice';

const props = defineProps<{ src: string }>();

const decoded = ref<number[] | null>(null);
const synthetic = computed(() => voiceWaveformBars(props.src, VOICE_BAR_COUNT));
const bars = computed(() => decoded.value ?? synthetic.value);

watch(() => props.src, () => { void decodeBars(); }, { immediate: true });

async function decodeBars(): Promise<void> {
  decoded.value = null;
  try {
    const Ctx = window.AudioContext;
    if (!Ctx) return;
    const buf = await (await fetch(props.src)).arrayBuffer();
    const ctx = new Ctx();
    const audioBuf = await ctx.decodeAudioData(buf);
    const pcm = audioBuf.getChannelData(0);
    decoded.value = voiceBucketRms(pcm, VOICE_BAR_COUNT);
    void ctx.close().catch(() => undefined);
  } catch { decoded.value = null; }
}

const node = computed(() =>
  basicRoot(voiceMessage({ src: props.src, bars: bars.value, barCount: VOICE_BAR_COUNT })),
);

const actions = {
  [VOICE_PLAY]: (): void => undefined,
};
</script>

<template>
  <ViewHost :node="node" :actions="actions" />
</template>

// apps/stage/components/VoiceMessage.tsx

import { useMemo } from 'react';
import { ViewHost } from '@stage-labs/kit/react-native/view-host';
import type { PayloadHandlers } from '@stage-labs/kit/kit';
import { basicRoot, voiceMessage, VOICE_PLAY } from '@views';
import { VOICE_BAR_COUNT, voiceWaveformBars } from '@stage-labs/client/xmtp/voice';
import { Box } from './layout';
import { useDecodedBars } from './VoiceMessage.barsCache';

interface Props { uri: string }

export function VoiceMessage({ uri }: Props): React.ReactElement {
  const synthetic = useMemo(() => voiceWaveformBars(uri, VOICE_BAR_COUNT), [uri]);
  const decoded = useDecodedBars(uri, VOICE_BAR_COUNT);
  const bars = decoded ?? synthetic;

  const node = basicRoot(voiceMessage({ src: uri, bars, barCount: VOICE_BAR_COUNT }));
  const actions: PayloadHandlers = { [VOICE_PLAY]: () => undefined };
  return (
    <Box margin={{ bottom: 6 }} style={{ alignSelf: 'flex-start' }}>
      <ViewHost node={node} actions={actions} />
    </Box>
  );
}
