// apps/app/components/settings/ExperimentalSettings.tsx
/** Settings → Experimental menu - a System-page-style list (same Kit ListView
 *  style as the main Settings menu) housing the not-yet-stable surfaces: the Kit
 *  theme/component gallery, the app Components gallery, and the Developer
 *  diagnostics console. Reached via /settings → "Experimental" row. */

import { Scroll as ScrollView } from '@metro-labs/kit/scroll';

import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Col } from '../layout';
import { Icon, type HeroIconName } from '@metro-labs/kit/icon';
import { Text } from '@metro-labs/kit/text';
import { ListView, ListViewItem } from '@metro-labs/kit/list-view';
import { useEffectiveColorScheme, usePalette } from '../../lib/theme';
import { SystemHeader } from '../system/SystemHeader';

type Href = '/settings/kit' | '/settings/components' | '/settings/developer';
const ROWS: { href: Href; label: string; icon: HeroIconName }[] = [
  { href: '/settings/kit', label: 'Kit', icon: 'colorSwatch' },
  { href: '/settings/components', label: 'Components', icon: 'viewGrid' },
  { href: '/settings/developer', label: 'Developer', icon: 'beaker' },
];

export function ExperimentalSettings(): React.ReactElement {
  const router = useRouter();
  const dark = useEffectiveColorScheme() === 'dark';
  const { text: fg, link: head, border } = usePalette();
  const sub = fg;
  const insets = useSafeAreaInsets();

  return (
    <Col surface="surface" flex={1}>
      <SystemHeader title="Experimental" dark={dark} fg={fg} head={head} border={border}/>
      <ScrollView contentContainerStyle={{ paddingBottom: 32 + insets.bottom }}>
        <ListView dark={dark}>
          {ROWS.map((row) => (
            <ListViewItem key={row.href} dark={dark} onPress={() => router.push(row.href)}>
              <Icon name={row.icon} size={22} color={head}/>
              <Col flex={1}>
                <Text size="xl" color={head}>{row.label}</Text>
              </Col>
              <Icon name="chevronRight" size={18} color={sub}/>
            </ListViewItem>
          ))}
        </ListView>
      </ScrollView>
    </Col>
  );
}

// apps/ui/src/views/settings/ExperimentalSettings.vue
<script setup lang="ts">

import { useRouter } from 'vue-router';
import { useKitPalette } from '@stage-labs/kit/vue/theme-context';
import type { HeroIconName } from '@stage-labs/kit/icons';

const router = useRouter();
const palette = useKitPalette();

const ROWS: { icon: HeroIconName; label: string; to: string }[] = [
  { icon: 'beaker', label: 'Developer', to: '/settings/developer' },
];
</script>

<template>
  <Col surface="surface" class="h-[100dvh]">
    <Row
      surface="toolbar"
      align="center"
      :gap="8"
      :padding="{ x: 12, y: 10 }"
      :style="{ borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: palette.border }"
    >
      <Pressable tag="button" type="button" class="p-1" @click="router.back()">
        <Icon name="arrowLeft" :size="22" :color="palette.text" />
      </Pressable>
      <Title size="sm">Experimental</Title>
    </Row>

    <Col class="flex-1 min-h-0 overflow-y-auto no-scrollbar pb-8">
      <Col
        class="w-[calc(100%-2rem)] mx-4 mt-5 rounded-xl overflow-hidden border bg-metro-surface-light dark:bg-metro-surface-dark"
        :style="{ borderColor: palette.border }"
      >
        <Pressable
          v-for="(row, i) in ROWS"
          :key="row.to"
          tag="button"
          type="button"
          class="w-full flex items-center gap-3 px-4 py-3.5 text-left
            hover:bg-metro-hover-light dark:hover:bg-metro-hover-dark transition-colors"
          :class="i === 0 ? '' : 'border-t'"
          :style="i === 0 ? {} : { borderColor: palette.border }"
          @click="router.push(row.to)"
        >
          <Icon :name="row.icon" :size="22" :color="palette.text" />
          <span class="flex-1 text-[17px] text-metro-head-light dark:text-metro-head-dark">{{ row.label }}</span>
          <Icon name="chevronRight" :size="18" :color="palette.sub" />
        </Pressable>
      </Col>
    </Col>
  </Col>
</template>
