// apps/stage/components/settings/ExperimentalSettings.tsx

import { Scroll as ScrollView } from '@stage-labs/kit/react-native/scroll';

import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Col } from '../layout';
import type { HeroIconName } from '@stage-labs/kit/react-native/icon';
import { ViewHost } from '@stage-labs/kit/react-native/view-host';
import type {
  ListViewNode,
  PayloadHandlers,
} from '@stage-labs/kit/kit';
import { backAction, settingsHeader, settingsNavAction, settingsNavRow, SETTINGS_NAV_PRESS } from '@views';
import { capabilities } from '../../lib/capabilities';
import { usePalette } from '../../lib/theme';

type Href = '/settings/kit' | '/settings/components' | '/settings/developer';
const ROWS: { href: Href; label: string; icon: HeroIconName }[] = [
  { href: '/settings/kit', label: 'Kit', icon: 'colorSwatch' },
  { href: '/settings/components', label: 'Components', icon: 'viewGrid' },
  { href: '/settings/developer', label: 'Developer', icon: 'beaker' },
];

export function ExperimentalSettings(): React.ReactElement {
  const { text: fg, link: head, border, toolbarBg } = usePalette();
  const insets = useSafeAreaInsets();

  const node: ListViewNode = {
    type: 'ListView',
    children: ROWS.map((row) =>
      settingsNavRow({
        label: row.label,
        iconStart: row.icon,
        pressType: SETTINGS_NAV_PRESS,
        payload: { href: row.href },
      }),
    ),
  };

  const headerNode = settingsHeader({
    title: 'Experimental',
    backColor: fg,
    titleColor: head,
    surface: toolbarBg,
    borderColor: border,
    safeTop: insets.top,
  });

  const actions: PayloadHandlers = {
    ...backAction(capabilities),
    ...settingsNavAction(capabilities),
  };

  return (
    <Col surface="surface" flex={1}>
      <ViewHost node={headerNode} actions={actions}/>
      <ScrollView contentContainerStyle={{ paddingBottom: 32 + insets.bottom }}>
        <ViewHost node={node} actions={actions}/>
      </ScrollView>
    </Col>
  );
}

// apps/ui/src/views/settings/ExperimentalSettings.vue
<script setup lang="ts">

import { computed } from 'vue';
import { useKitPalette } from '@stage-labs/kit/vue/theme-context';
import ViewHost from '@stage-labs/kit/vue/view-host';
import type { ListViewNode } from '@stage-labs/kit/kit';
import { backAction, settingsHeader, settingsNavAction, settingsNavRow, SETTINGS_NAV_PRESS } from '@stage-labs/views';
import { capabilities } from '@/lib/capabilities';

const palette = useKitPalette();

const headerNode = computed(() => settingsHeader({
  title: 'Experimental',
  backColor: palette.text,
  surface: palette.toolbarBg,
  borderColor: palette.border,
  safeTop: 0,
}));

const node = computed<ListViewNode>(() => ({
  type: 'ListView',
  children: [settingsNavRow({
    label: 'Developer',
    iconStart: 'beaker',
    pressType: SETTINGS_NAV_PRESS,
    payload: { to: '/settings/developer' },
  })],
}));

const actions = {
  ...backAction(capabilities),
  ...settingsNavAction(capabilities),
};
</script>

<template>
  <Col surface="surface" class="h-[100dvh]">
    <ViewHost :node="headerNode" :actions="actions" />

    <Col class="flex-1 min-h-0 overflow-y-auto no-scrollbar pb-8">
      <Col class="w-[calc(100%-2rem)] mx-4 mt-5">
        <ViewHost :node="node" :actions="actions" />
      </Col>
    </Col>
  </Col>
</template>
