// apps/app/components/settings/NotificationsSettings.tsx

import { useEffect, useState } from 'react';

import { Scroll as ScrollView } from '@stage-labs/kit/react-native/scroll';
import * as Notifications from 'expo-notifications';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Box, Col } from '../layout';
import { Caption } from '@stage-labs/kit/react-native/caption';
import { ChatKitRenderer } from '@stage-labs/kit/react-native/chatkit-renderer';
import type {
  ListViewNode,
  WidgetActionRegistry,
} from '@stage-labs/kit/chatkit';
import {
  settingsToggleRow,
  SETTINGS_TOGGLE_CHANGE,
} from '@stage-labs/views';
import { useEffectiveColorScheme, usePalette } from '../../lib/theme';
import { SystemHeader } from '../system/SystemHeader';
import { loadPushEnabled, setPushEnabled, subscribePushPref, isPushEnabledSync } from '../../lib/pushPref';
import { getOrCreateXmtpClient } from '../../modules/messaging';
import { registerPushWithDaemon, unregisterPushFromDaemon } from '../../lib/push';

export function NotificationsSettings(): React.ReactElement {
  const dark = useEffectiveColorScheme() === 'dark';
  const { text: fg, link: head, border } = usePalette();
  const sub = fg;
  const insets = useSafeAreaInsets();
  const [enabled, setEnabled] = useState(isPushEnabledSync());
  const [perm, setPerm] = useState<string>('undetermined');

  useEffect(() => {
    void loadPushEnabled().then(setEnabled);
    void Notifications.getPermissionsAsync().then(p => { setPerm(p.status); }).catch(() => undefined);
    return subscribePushPref(() => { setEnabled(isPushEnabledSync()); });
  }, []);

  const onToggle = (next: boolean): void => {
    setEnabled(next);
    void (async (): Promise<void> => {
      await setPushEnabled(next);
      try {
        const client = await getOrCreateXmtpClient('production');
        if (next) await registerPushWithDaemon(client);
        else await unregisterPushFromDaemon(client);
      } catch { }
      try { setPerm((await Notifications.getPermissionsAsync()).status); } catch { }
    })();
  };

  const permLabel = perm === 'granted'
    ? 'System notifications are allowed.'
    : perm === 'denied'
      ? 'Blocked in system settings — enable notifications for Metro in your OS settings.'
      : 'System permission will be requested when you enable push.';

  const node: ListViewNode = {
    type: 'ListView',
    children: [
      settingsToggleRow({
        label: 'Push notifications',
        name: 'push',
        checked: enabled,
        description: 'Get notified about new messages even when Metro is closed.',
        changeType: SETTINGS_TOGGLE_CHANGE,
      }),
    ],
  };

  const registry: WidgetActionRegistry = {
    [SETTINGS_TOGGLE_CHANGE]: (action) => {
      const next = action.payload.push;
      if (typeof next === 'boolean') onToggle(next);
    },
  };

  return (
    <Col surface="surface" flex={1}>
      <SystemHeader title="Notifications" dark={dark} fg={fg} head={head} border={border}/>
      <ScrollView contentContainerStyle={{ paddingBottom: 32 + insets.bottom }}>
        <Caption color={sub} style={{ paddingHorizontal: 16, paddingTop: 20, paddingBottom: 8 }}>
          PUSH NOTIFICATIONS
        </Caption>
        <Box>
          <ChatKitRenderer node={node} registry={registry}/>
        </Box>
        <Caption color={sub} style={{ paddingHorizontal: 16, paddingTop: 12 }}>
          {permLabel}
        </Caption>
      </ScrollView>
    </Col>
  );
}

// apps/ui/src/views/settings/NotificationsSettings.vue
<script setup lang="ts">

import { ref, computed, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useKitPalette } from '@stage-labs/kit/vue/theme-context';
import ChatKitRenderer from '@stage-labs/kit/vue/chatkit-renderer';
import type { ListViewNode, WidgetActionRegistry } from '@stage-labs/kit/chatkit';
import {
  settingsButtonRow, settingsValueRow, SETTINGS_BUTTON_PRESS,
} from '@stage-labs/views';

const router = useRouter();
const palette = useKitPalette();

const supported = typeof window !== 'undefined' && 'Notification' in window;
const permission = ref<NotificationPermission>(supported ? Notification.permission : 'denied');
const busy = ref(false);

onMounted(() => {
  if (supported) permission.value = Notification.permission;
});

async function requestPermission(): Promise<void> {
  if (!supported || busy.value) return;
  busy.value = true;
  try {
    permission.value = await Notification.requestPermission();
  } catch { } finally {
    busy.value = false;
  }
}

const statusLabel = computed<string>(() => {
  if (!supported) return "This browser doesn't support notifications.";
  if (permission.value === 'granted') return 'Browser notifications are allowed.';
  if (permission.value === 'denied') return 'Blocked in browser settings — enable notifications for this site to receive them.';
  return 'Allow browser notifications to be alerted about new messages while Stage is open.';
});

const DESC = 'Get notified about new messages while Stage is open in this browser.';

const node = computed<ListViewNode>(() => ({
  type: 'ListView',
  children: [permission.value === 'granted'
    ? settingsValueRow({ label: 'Browser notifications', value: 'Allowed' })
    : settingsButtonRow({
      label: 'Enable',
      description: DESC,
      clickType: SETTINGS_BUTTON_PRESS,
    })],
}));

const registry: WidgetActionRegistry = {
  [SETTINGS_BUTTON_PRESS]: () => { void requestPermission(); },
};
</script>

<template>
  <Col surface="surface" class="h-[100dvh]">
    <Row
      surface="toolbar"
      align="center"
      :gap="8"
      :padding="{ x: 12, y: 10 }"
      :style="{ borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: palette.border }"
    >
      <Pressable tag="button" type="button" class="p-1" @click="router.back()">
        <Icon name="arrowLeft" :size="22" :color="palette.text" />
      </Pressable>
      <Title size="sm">Notifications</Title>
    </Row>

    <Col class="flex-1 min-h-0 overflow-y-auto no-scrollbar pb-8">
      <!-- PUSH NOTIFICATIONS: mirrors mobile NotificationsSettings' single toggle card.
           The web Notification API has no background push, so this drives the
           per-site permission instead of a daemon registration; the permission state
           is the web-appropriate equivalent of mobile's OS permission line. -->
      <Text size="3xs" tag="div" class="text-metro-sub-light dark:text-metro-sub-dark px-4 pt-5 pb-2">NOTIFICATIONS</Text>
      <Col class="w-[calc(100%-2rem)] mx-4">
        <ChatKitRenderer :node="node" :registry="registry" />
      </Col>
      <Text size="2xs" tag="div" class="text-metro-sub-light dark:text-metro-sub-dark px-4 pt-3">
        {{ statusLabel }}
      </Text>
    </Col>
  </Col>
</template>
