// apps/ui/src/pages/Lines.vue
<script setup lang="ts">
interface Row { line: string; owner: string | null }

const rows = ref<Row[] | null>(null);
const errMsg = ref('');
const router = useRouter();

onMounted(async () => {
  const cfg = loadConfig();
  if (!isConfigured(cfg)) { errMsg.value = 'not configured — open Settings'; return; }
  const r = await fetchState(cfg.daemonUrl, cfg.token);
  if (!r.ok) { errMsg.value = `failed (${r.status}): ${r.error}`; return; }
  const data = r.data as { lines?: string[]; claims?: Record<string, string> };
  const lines = data.lines ?? [];
  const claims = data.claims ?? {};
  rows.value = lines.map(line => ({ line, owner: claims[line] ?? null }));
});

function open(line: string): void {
  void router.push({ name: 'activity', query: { chat: line } });
}
function short(s: string): string { return s.replace(/^metro:\/\//, ''); }
function stationOf(uri: string): string { return uri.match(/^metro:\/\/([^/]+)/)?.[1] ?? 'webhook'; }
</script>

<template>
  <div class="flex flex-col min-h-screen">
    <AppHeader />
    <div v-if="errMsg" class="flex-1 flex items-center justify-center p-6">
      <span>{{ errMsg }}</span>
    </div>
    <div v-else-if="!rows" class="flex-1 flex items-center justify-center p-6 text-metro-sub-light dark:text-metro-sub-dark">
      Loading…
    </div>
    <div v-else-if="rows.length === 0" class="flex-1 flex items-center justify-center p-6 text-metro-sub-light dark:text-metro-sub-dark">
      No lines seen yet.
    </div>
    <ul v-else class="flex-1">
      <li
        v-for="r in rows"
        :key="r.line"
        class="px-4 py-3 border-b border-metro-border-light dark:border-metro-border-dark
          bg-metro-surface-light dark:bg-metro-surface-dark hover:bg-metro-hover-light dark:hover:bg-metro-hover-dark
          cursor-pointer"
        @click="open(r.line)"
      >
        <div class="flex items-center gap-2.5">
          <StationIcon :station="stationOf(r.line)" />
          <div class="min-w-0 flex-1">
            <div class="font-mono text-sm truncate">{{ short(r.line) }}</div>
            <div :class="r.owner ? 'text-metro-ok' : 'text-metro-sub-light dark:text-metro-sub-dark'" class="text-xs mt-0.5">
              {{ r.owner ? `claimed by ${short(r.owner)}` : 'unclaimed' }}
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>
</template>

// apps/app/app/(tabs)/lines.tsx
/** Lines screen — one-shot `/api/state` snapshot. Tap a row to filter the Activity feed. */

import { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, Text, View, useColorScheme } from 'react-native';
import { useRouter } from 'expo-router';
import { StationIcon } from '../../components/StationIcon';
import { loadConfig, isConfigured } from '../../lib/config';
import { fetchState } from '../../lib/sse';
import type { StateSnapshot } from '../../lib/types';

type Row = { line: string; owner: string | null };

const stationOf = (uri: string): string => uri.match(/^metro:\/\/([^/]+)/)?.[1] ?? 'webhook';

export default function Lines(): React.ReactElement {
  const router = useRouter();
  const dark = useColorScheme() === 'dark';
  const fg = dark ? '#e8ecf2' : '#1a1f29';
  const sub = dark ? '#8a94a6' : '#5a6477';
  const bg = dark ? '#000000' : '#ffffff';
  const border = dark ? '#262c38' : '#e3e7ef';
  const rowBg = dark ? '#161a22' : '#fafbfd';
  const [rows, setRows] = useState<Row[] | null>(null);
  const [error, setError] = useState<string>('');

  useEffect(() => {
    void (async (): Promise<void> => {
      const cfg = await loadConfig();
      if (!isConfigured(cfg)) { setError('not configured — open Settings'); return; }
      const r = await fetchState(cfg.daemonUrl, cfg.token);
      if (!r.ok) { setError(`failed (${r.status}): ${r.error}`); return; }
      const data = r.data as StateSnapshot;
      const claims = data.claims ?? {};
      setRows((data.lines ?? []).map(line => ({ line, owner: claims[line] ?? null })));
    })();
  }, []);

  if (error) {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, backgroundColor: bg }}>
        <Text style={{ color: fg, fontSize: 15 }}>{error}</Text>
      </View>
    );
  }
  if (!rows) {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: bg }}>
        <ActivityIndicator />
      </View>
    );
  }

  return (
    <FlatList
      data={rows}
      keyExtractor={r => r.line}
      style={{ backgroundColor: bg }}
      ListEmptyComponent={
        <View style={{ padding: 32, alignItems: 'center' }}>
          <Text style={{ color: sub }}>No lines seen yet.</Text>
        </View>
      }
      renderItem={({ item }) => (
        <Pressable
          onPress={() => router.push({ pathname: '/', params: { chat: item.line } })}
          style={({ pressed }) => ({
            backgroundColor: pressed ? border : rowBg,
            flexDirection: 'row', alignItems: 'center', gap: 10,
            paddingHorizontal: 14, paddingVertical: 12,
            borderBottomWidth: 1, borderBottomColor: border,
          })}
        >
          <StationIcon station={stationOf(item.line)} />
          <View style={{ flex: 1, minWidth: 0 }}>
            <Text style={{ color: fg, fontSize: 14, fontFamily: 'monospace' }} numberOfLines={1}>
              {item.line.replace(/^metro:\/\//, '')}
            </Text>
            <Text style={{ color: item.owner ? '#83c989' : sub, fontSize: 12, marginTop: 4 }}>
              {item.owner ? `claimed by ${item.owner.replace(/^metro:\/\//, '')}` : 'unclaimed'}
            </Text>
          </View>
        </Pressable>
      )}
    />
  );
}
