// apps/ui/src/pages/Messenger.vue
<script setup lang="ts">
/** Messenger — direct chat with the assistant via POST /api/messenger/send. */

import type { Config } from '../lib/config';

const MESSENGER_LINE = 'metro://messenger/owner';
const MESSENGER_USER = 'metro://messenger/user/owner';

const cfg = ref<Config>(loadConfig());
const chat = ref<string | undefined>(MESSENGER_LINE);
const text = ref('');
const sending = ref(false);
const err = ref<string | null>(null);

const tail = useTail(cfg, chat);

const bubbles = computed(() => [...tail.events.value].reverse());

function fmtTs(ts: string): string {
  try { return new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: false }); }
  catch { return ts.slice(11, 16); }
}

async function sendMessenger(): Promise<void> {
  const body = text.value.trim();
  if (!body) return;
  sending.value = true; err.value = null;
  try {
    const res = await fetch(`${cfg.value.daemonUrl.replace(/\/$/, '')}/api/messenger/send`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${cfg.value.token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ text: body, as: 'user' }),
    });
    if (!res.ok) {
      const j = (await res.json().catch(() => ({}))) as { error?: string };
      err.value = j.error ?? `HTTP ${res.status}`;
    } else {
      text.value = '';
    }
  } catch (e) {
    err.value = (e as Error).message;
  } finally {
    sending.value = false;
  }
}

onMounted(() => { cfg.value = loadConfig(); tail.reconnect(); });
onBeforeUnmount(() => tail.stop());
</script>

<template>
  <div class="flex flex-col min-h-screen pb-[124px]">
    <AppHeader
      :status="tail.status.value"
      :errorMsg="tail.errMsg.value"
      :count="tail.events.value.length"
    />
    <div class="flex-1 px-3 py-3 flex flex-col gap-1.5">
      <div
        v-for="e in bubbles"
        :key="e.id"
        class="flex"
        :class="e.from === MESSENGER_USER ? 'justify-end' : 'justify-start'"
      >
        <div
          class="max-w-[78%] px-3.5 py-2 leading-snug text-[15px] rounded-2xl"
          :class="e.from === MESSENGER_USER
            ? 'bg-metro-fg-light dark:bg-white text-white dark:text-black rounded-br-md'
            : 'bg-metro-hover-light dark:bg-[#2a2d33] text-metro-fg-light dark:text-metro-fg-dark rounded-bl-md'"
        >
          <div>{{ e.text ?? '(no text)' }}</div>
          <div
            class="text-[10px] opacity-60 mt-0.5"
            :class="e.from === MESSENGER_USER ? 'text-right' : 'text-left'"
          >{{ fmtTs(e.ts) }}</div>
        </div>
      </div>
      <div v-if="bubbles.length === 0" class="p-8 text-center text-metro-sub-light dark:text-metro-sub-dark">
        Type a message below to start chatting.
      </div>
    </div>
    <div v-if="err" class="px-4 pt-2 text-xs text-metro-err fixed bottom-[124px] left-0 right-0">send failed: {{ err }}</div>
    <div class="fixed bottom-[60px] left-0 right-0 z-10
      border-t border-metro-border-light dark:border-metro-border-dark
      bg-metro-surface-light dark:bg-metro-surface-dark
      flex items-end gap-2 p-3">
      <textarea
        v-model="text"
        placeholder="Message the assistant…"
        rows="1"
        class="flex-1 resize-none min-h-[40px] max-h-[120px] bg-metro-bg-light dark:bg-metro-bg-dark
          border border-metro-border-light dark:border-metro-border-dark rounded-2xl px-4 py-2 text-sm outline-none
          focus:ring-2 focus:ring-metro-accent"
        @keydown.enter.exact.prevent="sendMessenger"
      />
      <button
        type="button"
        :disabled="sending || !text.trim()"
        class="bg-metro-accent hover:bg-metro-accent-hover text-black font-bold px-5 py-2 rounded-full
          disabled:opacity-50 min-w-[68px]"
        @click="sendMessenger"
      >{{ sending ? '…' : 'Send' }}</button>
    </div>
  </div>
</template>

// apps/app/app/(tabs)/messenger.tsx
/** Messenger — direct chat with the assistant via `POST /api/messenger/send`. */

import { useCallback, useMemo, useState } from 'react';
import {
  ActivityIndicator, FlatList, Pressable, Text, TextInput, View,
  useColorScheme,
} from 'react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import { EventRow } from '../../components/EventRow';
import { loadConfig, isConfigured, type Config } from '../../lib/config';
import { useTail } from '../../lib/sse';

const MESSENGER_LINE = 'metro://messenger/owner';

async function postMessenger(daemonUrl: string, token: string, text: string):
  Promise<{ ok: true } | { ok: false; error: string }>
{
  return new Promise(resolve => {
    const xhr = new XMLHttpRequest();
    xhr.open('POST', `${daemonUrl.replace(/\/$/, '')}/api/messenger/send`);
    xhr.setRequestHeader('Authorization', `Bearer ${token}`);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.onload = (): void => {
      if (xhr.status >= 200 && xhr.status < 300) return resolve({ ok: true });
      let msg = `HTTP ${xhr.status}`;
      try { msg = (JSON.parse(xhr.responseText) as { error?: string }).error ?? msg; } catch { /* */ }
      resolve({ ok: false, error: msg });
    };
    xhr.onerror = (): void => resolve({ ok: false, error: 'network error' });
    xhr.ontimeout = (): void => resolve({ ok: false, error: 'timeout' });
    xhr.timeout = 15_000;
    xhr.send(JSON.stringify({ text, as: 'user' }));
  });
}

export default function Messenger(): React.ReactElement {
  const router = useRouter();
  const dark = useColorScheme() === 'dark';
  const fg = dark ? '#e8ecf2' : '#1a1f29';
  const sub = dark ? '#8a94a6' : '#5a6477';
  const bg = dark ? '#0f1115' : '#ffffff';
  const border = dark ? '#262c38' : '#e3e7ef';

  const [cfg, setCfg] = useState<Config | null>(null);
  const [text, setText] = useState('');
  const [sending, setSending] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  useFocusEffect(useCallback(() => { void loadConfig().then(setCfg); }, []));

  const tailOpts = useMemo(() => ({
    daemonUrl: cfg?.daemonUrl ?? '', token: cfg?.token ?? '',
    chat: MESSENGER_LINE, includeWebhooks: false,
  }), [cfg]);

  const enabled = !!cfg && isConfigured(cfg);
  const { events } = useTail(tailOpts, enabled);
  /** Newest at the bottom for a chat UX; the FlatList is inverted so we render newest-first. */

  if (cfg && !isConfigured(cfg)) {
    return (
      <View style={{ flex: 1, padding: 24, gap: 12, justifyContent: 'center', backgroundColor: bg }}>
        <Text style={{ color: fg, fontSize: 18, fontWeight: '700' }}>Set up first</Text>
        <Text style={{ color: sub, lineHeight: 22 }}>
          Open Settings and configure the daemon URL + bearer token to chat with the assistant.
        </Text>
        <Pressable
          onPress={() => router.push('/settings')}
          style={{ backgroundColor: '#5aa9ff', paddingVertical: 12, borderRadius: 8, alignItems: 'center' }}
        >
          <Text style={{ color: '#fff', fontWeight: '700' }}>Open Settings</Text>
        </Pressable>
      </View>
    );
  }

  const canSend = !sending && !!text.trim();
  const send = async (): Promise<void> => {
    const body = text.trim();
    if (!body || !cfg) return;
    setSending(true); setErr(null);
    const r = await postMessenger(cfg.daemonUrl, cfg.token, body);
    setSending(false);
    if (r.ok) { setText(''); return; }
    setErr(r.error);
  };

  return (
    <View style={{ flex: 1, backgroundColor: bg }}>
      <FlatList
        data={events}
        keyExtractor={e => e.id}
        renderItem={({ item }) => (
          <EventRow
            entry={item}
            onPress={() => router.push({ pathname: '/event/[id]', params: { id: item.id, data: JSON.stringify(item) } })}
          />
        )}
        ListEmptyComponent={
          <View style={{ padding: 32, alignItems: 'center' }}>
            <Text style={{ color: sub }}>Type a message below to start chatting.</Text>
          </View>
        }
        keyboardShouldPersistTaps="handled"
      />
      {err ? (
        <Text style={{ color: '#d96868', fontSize: 12, paddingHorizontal: 14, paddingTop: 8 }}>
          send failed: {err}
        </Text>
      ) : null}
      <View style={{
        flexDirection: 'row', gap: 8, padding: 10, alignItems: 'flex-end',
        borderTopWidth: 1, borderTopColor: border,
      }}>
        <TextInput
          value={text}
          onChangeText={setText}
          placeholder="Message the assistant…"
          placeholderTextColor={sub}
          multiline
          style={{
            flex: 1,
            backgroundColor: dark ? '#16191f' : '#f3f5f9',
            color: fg, borderRadius: 18,
            paddingHorizontal: 14, paddingTop: 10, paddingBottom: 10,
            fontSize: 15, maxHeight: 120,
          }}
        />
        <Pressable
          onPress={() => void send()}
          disabled={!canSend}
          style={({ pressed }) => ({
            backgroundColor: pressed ? '#4a8fdf' : '#5aa9ff',
            opacity: canSend ? 1 : 0.5,
            paddingHorizontal: 16, paddingVertical: 10, borderRadius: 18,
            alignItems: 'center', justifyContent: 'center', minWidth: 60,
          })}
        >
          {sending ? <ActivityIndicator color="#fff" /> : (
            <Text style={{ color: '#fff', fontWeight: '700' }}>Send</Text>
          )}
        </Pressable>
      </View>
    </View>
  );
}
