// apps/ui/src/pages/Profile.vue
<script setup lang="ts">
/** Profile tab — wallet identity + Snapshot-hub profile (display name, bio,
 *  custom avatar, socials). Tap Edit to open the EIP-712 update sheet. */

import { getOrCreateXmtpClient, shortAddress, stampBoxAvatarUrl } from '../lib/xmtp';
import { loadCachedProfile, readProfile, type SnapshotProfile } from '../lib/profile';

const AVATAR_SIZE = 120;

const address = ref('');
const inboxId = ref('');
const profile = ref<SnapshotProfile>({});
const editing = ref(false);
const copyHint = ref<'address' | 'inboxId' | null>(null);

const displayName = computed(() =>
  profile.value.name?.trim() || (address.value ? shortAddress(address.value) : 'Loading…'),
);

onMounted(async () => {
  try {
    const client = await getOrCreateXmtpClient('production');
    address.value = client.accountIdentifier?.identifier ?? '';
    inboxId.value = client.inboxId ?? '';
    const cached = loadCachedProfile();
    if (cached) profile.value = cached;
    if (address.value) {
      const remote = await readProfile(address.value);
      if (remote) profile.value = remote;
    }
  } catch { /* leave fields blank */ }
});

async function copy(value: string, label: 'address' | 'inboxId'): Promise<void> {
  if (!value) return;
  try {
    await navigator.clipboard.writeText(value);
    copyHint.value = label;
    setTimeout(() => { copyHint.value = null; }, 1500);
  } catch { /* no clipboard permission */ }
}
</script>

<template>
  <div class="min-h-screen">
    <div class="flex items-center justify-between px-4 pt-4 pb-2">
      <h1 class="font-head text-xl text-metro-fg-light dark:text-metro-fg-dark">Profile</h1>
      <button
        v-if="address" type="button"
        class="font-head text-sm text-metro-fg-light dark:text-metro-fg-dark"
        @click="editing = true"
      >Edit</button>
    </div>

    <div class="flex flex-col items-center pt-6 pb-4">
      <img v-if="address"
        :src="stampBoxAvatarUrl(address, AVATAR_SIZE * 2)"
        alt=""
        :width="AVATAR_SIZE" :height="AVATAR_SIZE"
        class="rounded-full bg-metro-border-dark object-cover"
        :style="{ width: `${AVATAR_SIZE}px`, height: `${AVATAR_SIZE}px` }"
      />
      <div v-else class="rounded-full bg-metro-border-dark" :style="{ width: `${AVATAR_SIZE}px`, height: `${AVATAR_SIZE}px` }" />
      <div class="font-head text-lg text-metro-fg-light dark:text-metro-fg-dark mt-3.5">
        {{ displayName }}
      </div>
      <div v-if="profile.about"
        class="text-[13px] text-metro-sub-light dark:text-metro-sub-dark mt-1.5 px-6 text-center max-w-md">
        {{ profile.about }}
      </div>
    </div>

    <button
      v-if="address" type="button"
      class="block w-[calc(100%-2rem)] mx-4 mt-2 p-3 rounded-xl text-left
        bg-metro-surface-light dark:bg-metro-surface-dark
        border border-metro-border-light dark:border-metro-border-dark"
      @click="copy(address, 'address')"
    >
      <div class="text-[11px] text-metro-sub-light dark:text-metro-sub-dark">
        WALLET ADDRESS ({{ copyHint === 'address' ? 'copied!' : 'tap to copy' }})
      </div>
      <div class="text-[13px] text-metro-fg-light dark:text-metro-fg-dark mt-1 break-all">
        {{ address }}
      </div>
    </button>

    <button
      v-if="inboxId" type="button"
      class="block w-[calc(100%-2rem)] mx-4 mt-3 p-3 rounded-xl text-left
        bg-metro-surface-light dark:bg-metro-surface-dark
        border border-metro-border-light dark:border-metro-border-dark"
      @click="copy(inboxId, 'inboxId')"
    >
      <div class="text-[11px] text-metro-sub-light dark:text-metro-sub-dark">
        XMTP INBOX ID ({{ copyHint === 'inboxId' ? 'copied!' : 'tap to copy' }})
      </div>
      <div class="text-[13px] text-metro-fg-light dark:text-metro-fg-dark mt-1 truncate">
        {{ inboxId }}
      </div>
    </button>

    <EditProfileModal
      :open="editing" :address="address" :initial="profile"
      @close="editing = false"
      @saved="next => profile = next"
    />
  </div>
</template>

// apps/app/app/(tabs)/profile.tsx
/** Profile tab — wallet identity + Snapshot-hub profile (display name, bio,
 *  custom avatar, socials). Tap Edit to open the EIP-712 update sheet. */

import { useEffect, useState } from 'react';
import { Alert, Image, Pressable, Text, View } from 'react-native';
import * as Clipboard from 'expo-clipboard';
import { getOrCreateXmtpClient, shortAddress } from '../../lib/xmtp';
import { avatarRenderUrl } from '../../../_shared/profile/snapshot';
import { useEffectiveColorScheme } from '../../lib/theme';
import { usePushToken, type PushStatus } from '../../lib/push';
import {
  loadCachedProfile, readProfile, type SnapshotProfile,
} from '../../lib/profile';
import EditProfileModal from '../../components/EditProfileModal';

const AVATAR_SIZE = 120;

export default function Profile(): React.ReactElement {
  const dark = useEffectiveColorScheme() === 'dark';
  const fg = dark ? '#9f9fa3' : '#57606a';
  const head = dark ? '#ffffff' : '#000000';
  const sub = dark ? '#7a7a7e' : '#8a929d';
  const bg = dark ? '#0e0f10' : '#ffffff';
  const border = dark ? '#282a2d' : '#e4e4e5';
  const rowBg = dark ? '#282a2d' : '#e4e4e5';

  const [address, setAddress] = useState<string>('');
  const [inboxId, setInboxId] = useState<string>('');
  const [profile, setProfile] = useState<SnapshotProfile>({});
  const [loaded, setLoaded] = useState(false);
  const [editing, setEditing] = useState(false);
  const push = usePushToken();

  useEffect(() => {
    void (async (): Promise<void> => {
      try {
        const client = await getOrCreateXmtpClient('production');
        const addr = client.publicIdentity.identifier;
        setAddress(addr);
        setInboxId(client.inboxId);
        /** Local cache first so the UI doesn't flash a blank state on cold start;
         *  the hub fetch then promotes the canonical record. */
        const cached = await loadCachedProfile();
        if (cached) setProfile(cached);
        setLoaded(true);
        const remote = await readProfile(addr);
        if (remote) setProfile(remote);
      } catch { /* leave fields blank — render placeholder */ }
    })();
  }, []);

  const copy = (value: string, label: string): void => {
    void Clipboard.setStringAsync(value);
    Alert.alert('Copied', `${label} copied to clipboard`);
  };

  const displayName = profile.name?.trim() || shortAddress(address);

  return (
    <View style={{ flex: 1, backgroundColor: bg }}>
      <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingTop: 16, paddingBottom: 8 }}>
        <Text style={{ color: head, fontSize: 22, fontFamily: 'Calibre-Semibold' }}>Profile</Text>
        {address ? (
          <Pressable onPress={() => setEditing(true)} hitSlop={8}>
            <Text style={{ color: head, fontSize: 14, fontFamily: 'Calibre-Semibold' }}>Edit</Text>
          </Pressable>
        ) : null}
      </View>

      <View style={{ alignItems: 'center', paddingTop: 24, paddingBottom: 16 }}>
        {address && loaded ? (
          <Image
            source={{ uri: avatarRenderUrl(address, profile.avatar, AVATAR_SIZE * 2) }}
            style={{ width: AVATAR_SIZE, height: AVATAR_SIZE, borderRadius: AVATAR_SIZE / 2, backgroundColor: rowBg }}
          />
        ) : (
          <View style={{ width: AVATAR_SIZE, height: AVATAR_SIZE, borderRadius: AVATAR_SIZE / 2, backgroundColor: rowBg }} />
        )}
        <Text style={{ color: head, fontSize: 18, fontFamily: 'Calibre-Semibold', marginTop: 14 }}>
          {address ? displayName : 'Loading…'}
        </Text>
        {profile.about ? (
          <Text style={{ color: sub, fontSize: 13, marginTop: 6, paddingHorizontal: 24, textAlign: 'center', fontFamily: 'Calibre-Medium' }}>
            {profile.about}
          </Text>
        ) : null}
      </View>

      {address ? (
        <Pressable
          onPress={() => copy(address, 'Wallet address')}
          style={{ marginHorizontal: 16, marginTop: 8, padding: 12, borderRadius: 12, backgroundColor: rowBg, borderWidth: 1, borderColor: border }}
        >
          <Text style={{ color: sub, fontSize: 11, fontFamily: 'Calibre-Medium' }}>WALLET ADDRESS (tap to copy)</Text>
          <Text style={{ color: fg, fontSize: 13, marginTop: 4, fontFamily: 'Calibre-Medium' }}>{address}</Text>
        </Pressable>
      ) : null}

      {inboxId ? (
        <Pressable
          onPress={() => copy(inboxId, 'XMTP inbox id')}
          style={{ marginHorizontal: 16, marginTop: 12, padding: 12, borderRadius: 12, backgroundColor: rowBg, borderWidth: 1, borderColor: border }}
        >
          <Text style={{ color: sub, fontSize: 11, fontFamily: 'Calibre-Medium' }}>XMTP INBOX ID (tap to copy)</Text>
          <Text style={{ color: fg, fontSize: 13, marginTop: 4, fontFamily: 'Calibre-Medium' }} numberOfLines={1}>{inboxId}</Text>
        </Pressable>
      ) : null}

      <PushTokenCard status={push.status} token={push.token} error={push.error}
        onCopy={() => push.token && copy(push.token, 'FCM device token')}
        sub={sub} fg={fg} border={border} rowBg={rowBg} />

      <EditProfileModal
        visible={editing} onClose={() => setEditing(false)}
        onSaved={next => setProfile(next)}
        address={address} initial={profile} dark={dark}
      />
    </View>
  );
}

function PushTokenCard({ status, token, error, onCopy, sub, fg, border, rowBg }: {
  status: PushStatus; token: string | null; error: string | null; onCopy: () => void;
  sub: string; fg: string; border: string; rowBg: string;
}): React.ReactElement {
  const label = status === 'requesting' ? 'PUSH TOKEN (requesting permission…)'
    : status === 'denied' ? 'PUSH TOKEN (permission denied — enable in system settings)'
    : status === 'unavailable' ? 'PUSH TOKEN (no Play Services / not a real device)'
    : status === 'error' ? `PUSH TOKEN (error: ${error ?? 'unknown'})`
    : 'PUSH TOKEN (tap to copy)';
  const showSubtitle = status !== 'ready';
  const body = token ?? (showSubtitle ? 'Run `metro call xmtp register-push \'{"token":"…"}\'` on the daemon host after copying.' : '');

  return (
    <Pressable
      onPress={token ? onCopy : undefined}
      style={{
        marginHorizontal: 16, marginTop: 12, padding: 12,
        borderRadius: 12, backgroundColor: rowBg,
        borderWidth: 1, borderColor: border,
        opacity: status === 'ready' ? 1 : 0.7,
      }}
    >
      <Text style={{ color: sub, fontSize: 11, fontFamily: 'Calibre-Medium' }}>{label}</Text>
      {body ? (
        <Text style={{ color: fg, fontSize: 11, marginTop: 4, fontFamily: 'Calibre-Medium' }}
          numberOfLines={token ? 3 : undefined} selectable>
          {body}
        </Text>
      ) : null}
    </Pressable>
  );
}
